### ISSUE TITLE
Cannot load fordpass after upgrading to 2022.7

### ISSUE THREAD

**Issue by briis** [itchannel/fordpass-ha#191] opened 2022-07-02 07:19 UTC
I know 2022.7 is still beta, so here is a heads up that it won't work when upgrading to HA 2022.7.
Hope this can be finxed before the release.

I have the latest released version of fordpass installed.

```log
Logger: homeassistant.loader
Source: custom_components/fordpass/__init__.py:8
Integration: fordpass (documentation, issues)
First occurred: 08.50.45 (1 occurrences)
Last logged: 08.50.45

Unexpected exception importing component custom_components.fordpass
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/loader.py", line 599, in get_component
    cache[self.domain] = importlib.import_module(self.pkg_path)
  File "/usr/local/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/config/custom_components/fordpass/__init__.py", line 8, in <module>
    from dotted.collection import DottedDict
  File "/usr/local/lib/python3.10/site-packages/dotted/collection.py", line 154, in <module>
    class DottedList(DottedCollection, collections.MutableSequence):
AttributeError: module 'collections' has no attribute 'MutableSequence'
````

**Comment by itchannel** [comment] 2022-07-02 07:53
Duplicate of #190 

@briis already been fixed just haven't pushed to release branch yet 👍

**Closed by itchannel** 2022-07-02 07:53 UTC

**Comment by briis** [comment] 2022-07-02 09:48
🙏 Thanks
