### ISSUE TITLE
sensor unavailable

### ISSUE THREAD

**Issue by DennisHilhorst** [itchannel/fordpass-ha#226] opened 2022-12-12 15:43 UTC
Hi,

Since one of the last 2 or 3 updates I have issues that all my ford sensors are unavailable.
![image](https://user-images.githubusercontent.com/116731240/207087886-f8419c41-6f94-4e95-bf82-5ac67e838bd7.png)

This happens very hour or so... 3x refresh of 15 minutes it's OK and the next one not...

Could one of you look into this.

BR, Dennis

**Comment by ThePitaGyros** [comment] 2022-12-12 21:15
Hello Dennis,

I have the same problem.

It does not matter if I encrease the poll interval to 1800 (1/2h) or even 3600 (1h), the answers from the ford pass service always alternate between response and no response (= unavailable sensor data)

I increased the logging sensitivity for the ford pass integration to debug by adding the following lines to the the configuration.yaml...

```
logger:
  logs:
    custom_components.fordpass: debug
```

and got the following output...

```
poll interval 900 seconds - 15 minutes

(available data until 21:17)
...
2022-12-12 21:16:57.290 DEBUG (SyncWorker_14) [custom_components.fordpass.fordpass_new] No token, or has expired, requesting new token
2022-12-12 21:17:28.695 WARNING (MainThread) [custom_components.fordpass]
2022-12-12 21:17:28.700 WARNING (MainThread) [custom_components.fordpass] Error communicating with FordPass for myVIN
2022-12-12 21:17:28.704 ERROR (MainThread) [custom_components.fordpass] Error fetching fordpass data: Error communicating with FordPass for myVIN
2022-12-12 21:17:28.708 DEBUG (MainThread) [custom_components.fordpass] Finished fetching fordpass data in 31.420 seconds (success: False)
...
(unavailable data from 21:17 until 21:32)
...
2022-12-12 21:32:28.772 DEBUG (SyncWorker_13) [custom_components.fordpass.fordpass_new] No token, or has expired, requesting new token
2022-12-12 21:32:29.156 DEBUG (SyncWorker_13) [custom_components.fordpass.fordpass_new] {'access_token': 'longToken', 'refresh_token': 'longToken', 'ford_consumer_id': 'myId', 'expires_in': 1800, 'refresh_expires_in': 31556952, 'expiry_date': 1670878949.1566484}
2022-12-12 21:32:29.168 DEBUG (SyncWorker_13) [custom_components.fordpass.fordpass_new] Token is valid, continuing
2022-12-12 21:32:30.098 DEBUG (SyncWorker_7) [custom_components.fordpass.fordpass_new] Token is valid, continuing
2022-12-12 21:32:30.558 INFO (MainThread) [custom_components.fordpass] Restored connection to FordPass for myVIN
2022-12-12 21:32:30.559 INFO (MainThread) [custom_components.fordpass] Fetching fordpass data recovered
2022-12-12 21:32:30.559 DEBUG (MainThread) [custom_components.fordpass] Finished fetching fordpass data in 1.936 seconds (success: True)
...
2022-12-12 21:47:30.289 DEBUG (SyncWorker_0) [custom_components.fordpass.fordpass_new] Token is valid, continuing
2022-12-12 21:47:31.098 DEBUG (SyncWorker_14) [custom_components.fordpass.fordpass_new] Token is valid, continuing
2022-12-12 21:47:31.577 DEBUG (MainThread) [custom_components.fordpass] Finished fetching fordpass data in 1.289 seconds (success: True)
...
(available data from 21:32 until 22:03)
Manual refresh triggered
...
2022-12-12 22:01:09.607 DEBUG (SyncWorker_8) [custom_components.fordpass] Running Service
2022-12-12 22:01:09.610 DEBUG (SyncWorker_8) [custom_components.fordpass.fordpass_new] Token is valid, continuing
2022-12-12 22:01:10.816 DEBUG (SyncWorker_8) [custom_components.fordpass] Refresh Sent
2022-12-12 22:02:31.467 DEBUG (SyncWorker_6) [custom_components.fordpass.fordpass_new] No token, or has expired, requesting new token
2022-12-12 22:03:01.467 WARNING (MainThread) [custom_components.fordpass] 
2022-12-12 22:03:01.472 WARNING (MainThread) [custom_components.fordpass] Error communicating with FordPass for myVIN
2022-12-12 22:03:01.476 ERROR (MainThread) [custom_components.fordpass] Error fetching fordpass data: Error communicating with FordPass for myVIN
2022-12-12 22:03:01.478 DEBUG (MainThread) [custom_components.fordpass] Finished fetching fordpass data in 30.013 seconds (success: False)
...
(unavailable data from 22:03)
```

It seems that every second request for a new token fails - I get the exact same pattern for ignitionStatus like the one you posted in the picture above. All other sensors behave exactly the same.

This behaviour has occured for a while now - I cannot pinpoint the exact date when this started to happen, but I hope the log helps to narrow down the error.

Maybe someone else can post their log files here to confirm our finding?

The used versions are Home Assistant 2022.12.3 / Fordpass 1.40

Best regards,
Pita.

**Comment by itchannel** [comment] 2022-12-12 21:57
@DennisHilhorst @ThePitaGyros Can you please check your logs and look for any python errors such as "ConnectionTimeout" which should be in the same place as the HA errors you posted above. It won't show up if you filter the HA log by "Fordpass" but if you just scroll without filtering you should see some more verbose output. 

My initial thoughts would be it's timing out on your network when connecting to the Fordpass API.

**Comment by ThePitaGyros** [comment] 2022-12-12 22:55
Hello itchannel,

I did not see any timeouts from the fordpass component, but my default log level is warning, only custom_components.fordpass logs are increased to debug.

```
logger:
  default: warning
  logs:
    custom_components.fordpass: debug
```

Can you please specify which additional component(s) I should log with debug? I am afraid that if I set debug as default level, I will drown in logs.

Thank you for helping with this issue!
Best regards,
Pita

**Comment by DennisHilhorst** [comment] 2022-12-13 14:22
As you all can see, the unavailibility is for multiple sensors.
![image](https://user-images.githubusercontent.com/116731240/207358378-1abc8247-36f7-45fe-867a-3a3a4794436c.png)

I've added the logging of the last few hours:
`2022-12-13 13:04:56.851 DEBUG (MainThread) [custom_components.fordpass] 840
2022-12-13 13:04:56.851 DEBUG (MainThread) [custom_components.fordpass] username
2022-12-13 13:04:56.851 DEBUG (MainThread) [custom_components.fordpass] password
2022-12-13 13:04:56.851 DEBUG (MainThread) [custom_components.fordpass] vin
2022-12-13 13:04:56.851 DEBUG (MainThread) [custom_components.fordpass] region
2022-12-13 13:04:56.851 DEBUG (MainThread) [custom_components.fordpass] UK&Europe
2022-12-13 13:05:00.562 DEBUG (MainThread) [custom_components.fordpass] Finished fetching fordpass data in 3.710 seconds (success: True)
2022-12-13 13:05:10.460 DEBUG (MainThread) [custom_components.fordpass] Finished fetching fordpass data in 4.133 seconds (success: True)
2022-12-13 13:05:22.790 DEBUG (MainThread) [custom_components.fordpass] Finished fetching fordpass data in 1.462 seconds (success: True)
2022-12-13 13:19:23.640 DEBUG (MainThread) [custom_components.fordpass] Finished fetching fordpass data in 1.640 seconds (success: True)
2022-12-13 13:33:23.046 WARNING (MainThread) [custom_components.fordpass] ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))
2022-12-13 13:33:23.089 WARNING (MainThread) [custom_components.fordpass] Error communicating with FordPass for WF0FXXWPMHNS11060
2022-12-13 13:33:23.092 ERROR (MainThread) [custom_components.fordpass] Error fetching fordpass data: Error communicating with FordPass for WF0FXXWPMHNS11060
2022-12-13 13:33:23.093 DEBUG (MainThread) [custom_components.fordpass] Finished fetching fordpass data in 0.092 seconds (success: False)
2022-12-13 13:47:24.232 INFO (MainThread) [custom_components.fordpass] Restored connection to FordPass for WF0FXXWPMHNS11060
2022-12-13 13:47:24.232 INFO (MainThread) [custom_components.fordpass] Fetching fordpass data recovered
2022-12-13 13:47:24.232 DEBUG (MainThread) [custom_components.fordpass] Finished fetching fordpass data in 1.231 seconds (success: True)
2022-12-13 14:01:25.769 DEBUG (MainThread) [custom_components.fordpass] Finished fetching fordpass data in 1.768 seconds (success: True)
2022-12-13 14:15:26.345 DEBUG (MainThread) [custom_components.fordpass] Finished fetching fordpass data in 1.345 seconds (success: True)
2022-12-13 14:29:26.017 WARNING (MainThread) [custom_components.fordpass] ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))
2022-12-13 14:29:26.018 WARNING (MainThread) [custom_components.fordpass] Error communicating with FordPass for WF0FXXWPMHNS11060
2022-12-13 14:29:26.018 ERROR (MainThread) [custom_components.fordpass] Error fetching fordpass data: Error communicating with FordPass for WF0FXXWPMHNS11060
2022-12-13 14:29:26.019 DEBUG (MainThread) [custom_components.fordpass] Finished fetching fordpass data in 0.019 seconds (success: False)
2022-12-13 14:43:27.442 INFO (MainThread) [custom_components.fordpass] Restored connection to FordPass for WF0FXXWPMHNS11060
2022-12-13 14:43:27.442 INFO (MainThread) [custom_components.fordpass] Fetching fordpass data recovered
2022-12-13 14:43:27.442 DEBUG (MainThread) [custom_components.fordpass] Finished fetching fordpass data in 1.442 seconds (success: True)
2022-12-13 14:57:28.261 DEBUG (MainThread) [custom_components.fordpass] Finished fetching fordpass data in 1.261 seconds (success: True)
2022-12-13 15:11:29.194 DEBUG (MainThread) [custom_components.fordpass] Finished fetching fordpass data in 1.193 seconds (success: True)
`

**Comment by ThePitaGyros** [comment] 2022-12-13 14:33
Hello DennisHilhorst,

I would not post VIN numbers.
It seems like you have the save behaviour that I encountered.
I formatted your output for better readability...

Best regards,
Pita

```
2022-12-13 13:04:56.851 DEBUG (MainThread) [custom_components.fordpass] 840 
2022-12-13 13:04:56.851 DEBUG (MainThread) [custom_components.fordpass] username 
2022-12-13 13:04:56.851 DEBUG (MainThread) [custom_components.fordpass] password 
2022-12-13 13:04:56.851 DEBUG (MainThread) [custom_components.fordpass] vin 
2022-12-13 13:04:56.851 DEBUG (MainThread) [custom_components.fordpass] region 
2022-12-13 13:04:56.851 DEBUG (MainThread) [custom_components.fordpass] UK&Europe 
2022-12-13 13:05:00.562 DEBUG (MainThread) [custom_components.fordpass] Finished fetching fordpass data in 3.710 seconds (success: True) 
2022-12-13 13:05:10.460 DEBUG (MainThread) [custom_components.fordpass] Finished fetching fordpass data in 4.133 seconds (success: True) 
2022-12-13 13:05:22.790 DEBUG (MainThread) [custom_components.fordpass] Finished fetching fordpass data in 1.462 seconds (success: True) 
2022-12-13 13:19:23.640 DEBUG (MainThread) [custom_components.fordpass] Finished fetching fordpass data in 1.640 seconds (success: True) 
2022-12-13 13:33:23.046 WARNING (MainThread) [custom_components.fordpass] ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response')) 
2022-12-13 13:33:23.089 WARNING (MainThread) [custom_components.fordpass] Error communicating with FordPass for myVIN 
2022-12-13 13:33:23.092 ERROR (MainThread) [custom_components.fordpass] Error fetching fordpass data: Error communicating with FordPass for myVIN 
2022-12-13 13:33:23.093 DEBUG (MainThread) [custom_components.fordpass] Finished fetching fordpass data in 0.092 seconds (success: False) 
2022-12-13 13:47:24.232 INFO (MainThread) [custom_components.fordpass] Restored connection to FordPass for myVIN 
2022-12-13 13:47:24.232 INFO (MainThread) [custom_components.fordpass] Fetching fordpass data recovered 
2022-12-13 13:47:24.232 DEBUG (MainThread) [custom_components.fordpass] Finished fetching fordpass data in 1.231 seconds (success: True) 
2022-12-13 14:01:25.769 DEBUG (MainThread) [custom_components.fordpass] Finished fetching fordpass data in 1.768 seconds (success: True) 
2022-12-13 14:15:26.345 DEBUG (MainThread) [custom_components.fordpass] Finished fetching fordpass data in 1.345 seconds (success: True) 
2022-12-13 14:29:26.017 WARNING (MainThread) [custom_components.fordpass] ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response')) 
2022-12-13 14:29:26.018 WARNING (MainThread) [custom_components.fordpass] Error communicating with FordPass for myVIN 
2022-12-13 14:29:26.018 ERROR (MainThread) [custom_components.fordpass] Error fetching fordpass data: Error communicating with FordPass for myVIN 
2022-12-13 14:29:26.019 DEBUG (MainThread) [custom_components.fordpass] Finished fetching fordpass data in 0.019 seconds (success: False) 
2022-12-13 14:43:27.442 INFO (MainThread) [custom_components.fordpass] Restored connection to FordPass for myVIN 
2022-12-13 14:43:27.442 INFO (MainThread) [custom_components.fordpass] Fetching fordpass data recovered 
2022-12-13 14:43:27.442 DEBUG (MainThread) [custom_components.fordpass] Finished fetching fordpass data in 1.442 seconds (success: True) 
2022-12-13 14:57:28.261 DEBUG (MainThread) [custom_components.fordpass] Finished fetching fordpass data in 1.261 seconds (success: True) 
2022-12-13 15:11:29.194 DEBUG (MainThread) [custom_components.fordpass] Finished fetching fordpass data in 1.193 seconds (success: True)
```

**Comment by ThePitaGyros** [comment] 2022-12-20 08:58
@itchannel Hello ITCHannel,

this issue is still open with no further clues or insights in the logs or the front end on what the problem is.

Can you provide some possibilities what can be done here? Is there a configuration file, where we can change the timeout? Are there other configuration options that allow us to tweak the behaviour of the addon?

Currently only the polling interval can be changed via the frontend, which does not lead to any change in the bahaviour (switching between available sensor data and unavailable sensor data).

I would appreciate any help :-)
Thank you and Merry Christmas!
Pita

**Comment by itchannel** [comment] 2022-12-20 11:04
It's one of these niche issues where it's a pain to nail down what might be causing it. Looking at the logs it seems like the connection to the vehicle enquiry API is timing out for you. I did experience a similar issue in my dev environment a long time ago and it was because of a docker networking bug which caused the dns lookup to fail every so often. 

It's very weird that yours is every hour. 

Can you provide the following information @ThePitaGyros @DennisHilhorst just so I can see if you both have anything in common. 

- HA Version/instance (HAOS, Docker, PI etc)
- HA software version
- Country located in
- Region selected in Fordpass integration
- How long this issue has been happening
- Is it always every hour?
- ISP and DNS server used if using public dns e.g 1.1.1.1, 8.8.8.8

If I can find something in common we can go from there, but with the API closing the request it could be on Fords end which would be a nightmare to diagnose as this isn't an official supported integration.

**Comment by DennisHilhorst** [comment] 2022-12-20 12:16
- HA Version/instance (HAOS, Docker, PI etc)
   Docker on Synology (homeassistant/home-assistant:latest)
- HA software version
   Home Assistant 2022.11.4 (Frontend-versie: 20221108.0 - latest)
   HACS (version 1.29.0)
- Country located in
   The Netherlands
- Region selected in Fordpass integration
   ?!? I cannot see this option
- How long this issue has been happening
   I thought that I update from 1.36 to 1.39... So until 1.36 I had no issue's
- Is it always every hour?
   Mostely yes... but not always (see screenshot)
   ![image](https://user-images.githubusercontent.com/116731240/208664729-16c95c4b-fa04-4c9c-a1b8-50f7df00783a.png)
- ISP and DNS server used if using public dns e.g 1.1.1.1, 8.8.8.8
   ? Where can I look up that value?

**Comment by ThePitaGyros** [comment] 2022-12-20 12:54
Hello @itchannel. Thank you for your answer!

Here is the information you requested...

- HA Version/instance (HAOS, Docker, PI etc): Home Assistant Supervised on Raspberry PI (Ubuntu 22.04.1 LTS with Kernel 5.15.0-1021 and Python 3.10.7)
- HA software version: core-2022.12.7
- Country located in: Germany
- Region selected in Fordpass integration: UK&Europe
- How long this issue has been happening: Cannot really say - had this at least since beginning of December this year.
- Is it always every hour? It alternates from unavailable to available. If I change the polling interval - I tried 10 min., 15 min. 30 min. and 60 min. - the pattern does not change.
- ISP and DNS server used if using public dns e.g 1.1.1.1, 8.8.8.8: ISP is 1&1. I use its DNS servers.

Hope this helps.

**Comment by dewdrinker19** [comment] 2023-02-10 23:26
Hello, I have noticed this issue on my Docker installation test, but my Home Assistant OS installation never says unavailable.  I have disabled the integration in Home Assistant OS wher it works flawlessly, and installed/enabled in Home Assistant Container in Docker

--HA Version/instance (HAOS, Docker, PI etc)
Docker - Windows Docker Desktop

--HA software version
Home Assistant 2023.2.3
Frontend 20230202.0 - latest
HACS 1.30.1
fordpass-ha 1.42

--Country located in
United States

--Region selected in Fordpass integration
I don't see this option anywhere

--How long this issue has been happening
Only after trying Docker Installation a past few days, OS seems to work fine

--Is it always every hour?
I do not see anything consistent, but it does sometimes work and sometimes show as unavailable

Here is one of the errors in the logs:

Logger: custom_components.fordpass
Source: helpers/update_coordinator.py:182
Integration: Fordpass ([documentation](https://github.com/itchannel/fordpass-ha), [issues](https://github.com/itchannel/fordpass-ha/issues))
First occurred: February 8, 2023 at 4:44:42 PM (62 occurrences)
Last logged: 2:22:12 PM

Error fetching fordpass data: Error communicating with FordPass for VIN-WAS-HERE

**Comment by itchannel** [comment] 2023-10-19 09:58
Closing as old issue. Please re-open a new one if issue still exists.

**Closed as completed by itchannel** 2023-10-19 09:58 UTC
