### ISSUE TITLE
1.53-Beta6 - Inconsistent Distance to Empty between Two Vehicles

### ISSUE THREAD

**Issue by ziptbm** [itchannel/fordpass-ha#314] opened 2023-10-11 13:07 UTC
@itchannel creating this as a separate issue per your guidance in the main thread discussing the API change and your incredible quick fixes.

I've got two different Ford EVs ([JSON Files in this post](https://github.com/itchannel/fordpass-ha/issues/303#issuecomment-1756495844)) and I'm seeing inconsistent reporting of the Distance to Empty sensor between the two.  My Mach-E is showing 5 miles until empty (it's at 90% charge and FordPass app shows 228 miles currently) while my Lightning is showing 276 miles until empty (it's at 90% charge and FordPass app shows 276 miles currently).  The battery charge attribute under each Distance to Empty Sensor shows 90, and the Fuel entity shows 90% for each.  It's interesting that it's correct for one vehicle, but incorrect for the other.

I was running debug logging and have the file, however I noticed in the file it has a bunch of sensitive information like GPS coordinates of charging locations, VIN, email addresses, etc., so let me know what part of this log I need extract that would be helpful.

On a related note, I have a variety of template sensors previously built out for calculating time to charge to 90%, 100%, energy remaining, etc. that were all based off of a template sensor that pulled an attribute from the elveh sensor.  It looks like this is possible again now since there is a charge value under that sensor, but I'm wondering if we expect to have Fuel to report battery charge once the dust settles.  It's clear that the Battery percentage is the 12V battery, not the high voltage one.

Here are screenshots of each vehicle in Home Assistnt.

<img width="649" alt="Screenshot 2023-10-11 at 08 59 12" src="https://github.com/itchannel/fordpass-ha/assets/46136563/c3d65eea-feb9-4c49-8d1a-b2d42cba6acf">
<img width="649" alt="Screenshot 2023-10-11 at 08 59 07" src="https://github.com/itchannel/fordpass-ha/assets/46136563/7176e5f4-dd84-459a-87a6-ee9160e18079">

**Comment by slopemad** [comment] 2023-10-11 13:45
Same here.  MY2023 Mach-E.  The battery is 100% full with 300 miles to empty, but the sensor in HA showing 1 mile.  It was reporting correctly until about 9am, the screenshot shows it dropping off.  I'm on Beta6.
<img width="499" alt="Screenshot 2023-10-11 at 14 42 19" src="https://github.com/itchannel/fordpass-ha/assets/118896510/86650f42-3557-4c3e-8e0a-9ab60f05fe3d">

**Comment by SquidBytes** [comment] 2023-10-11 18:06
I've been looking into this. 
The code looks good for the range, and the fact that it works sometimes, but doesn't others is confusing.
I think it might be related to not getting the data from the new API.

If, while seeing the issue, you could attach your json it would help figure out why its showing that.

Easy json grabber I made: https://github.com/SquidBytes/fordpass-ha/blob/master/custom_components/fordpass/autonomicData.py

> I was running debug logging and have the file, however I noticed in the file it has a bunch of sensitive information like GPS coordinates of charging locations, VIN, email addresses, etc., so let me know what part of this log I need extract that would be helpful.

My script will automatically redact personal information and GPS, it wont be from the logs, it will be a standalone json.

From looking into the sensor.py I don't see many log sections so I don't think the log will be helpful - but I could be wrong

**Comment by SquidBytes** [comment] 2023-10-11 18:21
> I'm wondering if we expect to have Fuel to report battery charge once the dust settles. It's clear that the Battery percentage is the 12V battery, not the high voltage one.
Battery is the 12v
Battery Charge attribute under elVeh is your State of Charge
ALSO, like you thought, Fuel can now be used as it also reports State of Charge

Also related, I'm not sure what itchannel wants to do moving forward for Battery State of Charge, but I worked on a Charging sensor that gets the data I could find, because I like to see it all. #316

> I have a variety of template sensors previously built out for calculating time to charge to 90%, 100%, energy remaining, etc. that were all based off of a template sensor that pulled an attribute from the elveh sensor.
Try these just moving to the Fuel sensor

**Comment by mojomojoman** [comment] 2023-10-12 01:11
i dont think its the API causing the DTE for EVs to fluctuate. I think its something in beta 6.

put this in config.yaml:
```
template:
  - sensor:
      - name: "Mach-E Range"
        unique_id: sensor_fordpass_elveh_range
        state: "{{states('sensor.fordpass_elveh')}}"
        unit_of_measurement: "mi"
        device_class: distance
        icon: mdi:gauge
```

then you'll have a separate entity you can track with a graph. here's mine:

![image](https://github.com/itchannel/fordpass-ha/assets/67213346/bc2147be-b6fe-4006-9148-bcc218e28591)

i can almost watch it go up and down on my card every few minutes.  meanwhile the ford app and @SquidBytes Autonomic.py script values have remained constant at ~255 miles (409 km) across multiple samplings.  I have not driven the car all day so the graph should be a solid line across.

**Comment by SquidBytes** [comment] 2023-10-12 01:25
So my script is just saving the json data, rather than using it for fordpass-ha sensors. It's useful to see what data is there at specific times, which can help debug code.

I'll look into this when I get time, because I have access to EV data 24/7.

I know itchannel is also doing a bunch of changes and reworking things because the API is now vastly different.

The new API is both a blessing and a curse. There is a bunch of super cool (to me at least) data that can be used. But it also requires a ton of changes, testing, and debugging.

**Comment by mojomojoman** [comment] 2023-10-12 01:58
yeah i can see that. and i was looking at your branch and liked some of the changes like the charging status stuff. i really dont know any python but was able to hack a working version of sensor.py that had ALL the xev sensors in it.  I was just adding them as attribs to elveh.  then I updated to beta6 and overwrote it all and then got distracted with that pesky day job thing i have to do.

I personally am thinking now we should break all these things out into individual sensors with proper types and classes.  would be a lot of work.  we'd have to parse all those json files and figure out all possible sensors returned in the "metrics" array across the various cars.  I see 63 main entries but then you've got nested data like "doorStatus" which has an additional 6 nested entries for me.  If we had them all in some kind of mapping table that we could reference then most of the work in sensor.py would be reduced to matching sensors retrieved against the table and setting them accordingly.  i.e. table columns could be like:  APIEntity, HASensorName, HADataType, HADeviceClass

Maybe too ambitious a project for me as I'd literally have to learn python as I went and this is no "hello world project". lol. Maybe I'll just have to make myself content with hacking in the bits and pieces of data I see in your json files that i want but dont have in HA.  Would like to get to the bottom of the DTE thing in Beta6 though. Otherwise I'll have to roll back to an older version and build my own tweaks from there.

**Comment by SquidBytes** [comment] 2023-10-12 02:13
> got distracted with that pesky day job thing i have to do.

Same lol, so I understand 

> I personally am thinking now we should break all these things out into individual sensors with proper types and classes.

I'm, with the help of itchannel, in the process of looking into dynamic sensors. This way they would populate based on vehicle capabilities, and not crowd ICE vehicles with EV sensors.

This would ideally allow for EV sensors for every item returned from the json; provided the vehicle supports it.

Personally I would love to be able to log everything like:
High Voltage battery sensors
Battery temperatures 
Charging locations
Charging costs
Charging speeds
Regenerative breaking returns
Trip info 
Etc 

I'm a data nerd, and want to display all this data in a nice graph (similar to my side project LightningROD) using Home assistant as the vessel for this data (because itchannel has the hard parts mostly done, and this integration is great)

**Comment by itchannel** [comment] 2023-10-12 02:16
Please try Beta 7. I'm wondering if the inconsistency was caused by another bug. 

As in the code I'm only grabbing the value from the API and displaying it in the sensor I don't change anything at all.

**Comment by ziptbm** [comment] 2023-10-12 02:22
> Please try Beta 7. I'm wondering if the inconsistency was caused by another bug.
> 
> As in the code I'm only grabbing the value from the API and displaying it in the sensor I don't change anything at all.

Thanks.

Just installed 7 and my Mach-E shows 89 miles, but it actually has 231 estimated range at the moment.  My Lightning shows 276, however the  app shows 277… interesting.

**Comment by itchannel** [comment] 2023-10-12 02:30
Do you have different conversion set in integration options. It's unique options per car

![image](https://github.com/itchannel/fordpass-ha/assets/5840973/c377f04a-c3a6-422c-b596-f57835838d0d)


This is the piece of code for the Elveh sensor which is displaying your range

```
            if self.sensor == "elVeh":
                if "xevBatteryRange" in self.data:
                    if self.fordoptions[CONF_DISTANCE_UNIT] is not None:
                        if self.fordoptions[CONF_DISTANCE_UNIT] == "mi":
                            return round(
                                float(self.data["xevBatteryRange"]["value"]) / 1.60934
                            )
                        return float(self.data["xevBatteryRange"]["value"])
                    return float(self.data["xevBatteryRange"]["value"])
                return "Unsupported"
```

Also I compared your two json files you posted earlier and the values for the range were below, have you driven the car since posting?
MachE (316KM in miles is 196miles)
```
        "xevBatteryRange": {
            "updateTime": "2023-10-10T14:45:33Z",
            "oemCorrelationId": "94132",
            "value": 316.9
        },
```

Lightning (436km in miles is 270.9) 
```
        "xevBatteryRange": {
            "updateTime": "2023-10-10T17:12:49Z",
            "oemCorrelationId": "76083",
            "value": 436.80002
        },
```

**Comment by ziptbm** [comment] 2023-10-12 02:35
Both vehicles are set to PSI and mi.  

Yes, both have been driven and have had charging since I ran the scripts yesterday, but I believe only 30 miles or so since then.

**Comment by mojomojoman** [comment] 2023-10-12 02:48
> Please try Beta 7. I'm wondering if the inconsistency was caused by another bug.
> 
> As in the code I'm only grabbing the value from the API and displaying it in the sensor I don't change anything at all.

Sorry for the late reply. 
No change with beta 7 or at least its still being weird.  It started up with 159 mi then within seconds started fluctuating again now its flatlined at 1.  

![image](https://github.com/itchannel/fordpass-ha/assets/67213346/d232fccd-9414-48c0-afcd-c506fba40ee4)

the spike is when i rebooted for beta 7.  It should read 254 miles (409 km).

**Comment by mojomojoman** [comment] 2023-10-12 02:50
My fordpass options: 
![image](https://github.com/itchannel/fordpass-ha/assets/67213346/299927eb-6508-43fe-a621-c2280b6ed259)

**Comment by itchannel** [comment] 2023-10-12 02:54
@mojomojoman polling every 60 seconds is risky and could result in a ban. 

Can you enable debugging then run it for 10mins and either provide the log or look through to see if the value of "xevBatteryRange" is changing in the return json (Big string with loads of vehicle details)

I can't replicate this issue on my end.

**Comment by mojomojoman** [comment] 2023-10-12 02:57
yeah i should probably increase that polling interval never got me in trouble yet but no reason to push it.

I did just pull fresh json data and here's the xev values.  i've checked it repeatedly throughout the day though and xevBatteryRange has not budged from 409 km which is correct.

![image](https://github.com/itchannel/fordpass-ha/assets/67213346/9400aa2a-4502-48df-9c98-7e46fe72c506)

I'll turn on the debugging and see what i can get.

**Comment by itchannel** [comment] 2023-10-12 03:08
Can you do me a favour and swap out the code below on lines 244 - 256 of sensor.py. New code should look like this 

```
            if self.sensor == "fuel":
                if "fuelRange" in self.data:
                    if self.fordoptions[CONF_DISTANCE_UNIT] == "mi":
                        self.data["fuelRange"]["value"] = round(
                            float(self.data["fuelRange"]["value"]) / 1.60934
                        )
                    return {"fuelRange": self.data["fuelRange"]["value"]}
                elif "xevBatteryRange" in self.data:
                    if self.fordoptions[CONF_DISTANCE_UNIT] == "mi":
                        return {"batteryRange": round(
                            float(self.data["xevBatteryRange"]["value"]) / 1.60934
                        )}
                    return {"batteryRange": self.data["xevBatteryRange"]["value"]}
```

The issue was I was rewriting the conversion back to the data variable which resulted in it dividing all the time.

**Comment by mojomojoman** [comment] 2023-10-12 03:09
Something just occurred to me.  Since this started, after I reload fordpass it always starts at around 159 miles.  it SHOULD be 254 or 255. If i do a km to mi conversion on 255 its 158.45.  So maybe the value is getting double converted somehow.  That doesnt explain the fluctuating unless its getting converted again each time it polls or something.

oh. sure. just saw your post while i was typing this. will try it now.

**Comment by itchannel** [comment] 2023-10-12 03:11
> Something just occurred to me. Since this started, after I reload fordpass it always starts at around 159 miles. it SHOULD be 254 or 255. If i do a km to mi conversion on 255 its 158.45. So maybe the value is getting double converted somehow. That doesnt explain the fluctuating unless its getting converted again each time it polls or something.
> 
> oh. sure. just saw your post while i was typing this. will try it now.

Make sure you refresh my comment first as I just updated another bit as well.

**Comment by mojomojoman** [comment] 2023-10-12 03:13
oh? which line changed?

**Comment by mojomojoman** [comment] 2023-10-12 03:14
Lookin good so far: 
![image](https://github.com/itchannel/fordpass-ha/assets/67213346/aa6b5ecd-d8c8-4376-9c99-b89c53009d1a)

**Comment by itchannel** [comment] 2023-10-12 03:14
Should now have this, if you grab the code from my above comment it's corect

```
                        return {"fuelRange:": round(
                            float(self.data["fuelRange"]["value"]) / 1.60934
                        )}
```

**Comment by itchannel** [comment] 2023-10-12 03:14
Certainly an obscure little bug, finally managed to debug and replicate it :)

**Comment by mojomojoman** [comment] 2023-10-12 03:18
yeah. and i was like no way is ford changing that data that quickly, they never poll the car that frequently unless i'm hammering away in the app or something so i figured it had to be happening in HA somewhere because i was basically see the number jump around every 60 seconds because of my low polling interval.

and just to confirm this is what i have in my sensor.py:

```
            if self.sensor == "fuel":
                if "fuelRange" in self.data:
                    if self.fordoptions[CONF_DISTANCE_UNIT] == "mi":
                        return {"fuelRange:": round(
                            float(self.data["fuelRange"]["value"]) / 1.60934
                        )}
                    return {"fuelRange": self.data["fuelRange"]["value"]}
                elif "xevBatteryRange" in self.data:
                    if self.fordoptions[CONF_DISTANCE_UNIT] == "mi":
                        return {"batteryRange": round(
                            float(self.data["xevBatteryRange"]["value"]) / 1.60934
                        )}
                    return {"batteryRange": self.data["xevBatteryRange"]["value"]}
```

**Comment by mojomojoman** [comment] 2023-10-12 03:19
Holding stable now at 254 so you can probably commit that change but I'll keep an eye on it JIC and let you know.

**Comment by itchannel** [comment] 2023-10-12 03:28
I've got it running on my test instance too. Looks like it's fixed it. Thanks for the challenge, definitely a harder bug to track down than normal.

**Comment by mojomojoman** [comment] 2023-10-12 03:33
yeah i was staring at the code trying to figure it out myself and not getting very far. python is both easy to read and mind boggling for me.  I mean I do a lot of powershell scripting and in a former life some visual basic programming but like never did anything in python.  IF statements with no ELSE and no open and closing blocks.  I guess its just intuited that its the ELSE line by the indentation?  since when should whitespace matter? madness.  pure madness.  but i guess thats one way to force good code indentation hygiene.

**Comment by SquidBytes** [comment] 2023-10-12 03:38
I'm still learning as I do things. I'm having fun trying to integrate new things. It is incredibly satisfying to write some code, refresh HomeAssisnt, and see a sensor I made show up. My mind is racing with new ideas of sensors for logging all the stats of my vehicle.

**Comment by mojomojoman** [comment] 2023-10-12 03:45
lol. i know right.  i got so impatient after i looked at your json dump that I hacked a bunch of code in sensor.py so i could see ALL THE PRECIOUS DATAS... 

I just found the appropriate section and dumped this in:
```
            if self.sensor == "elVeh":
                if self.data["xevBatteryStateOfCharge"] is None:
                    return None
                elecs = {}
                if (self.data["xevBatteryActualStateOfCharge"] is not None and self.data["xevBatteryActualStateOfCharge"]["value"] is not None):
                    elecs["Battery Actual State Of Charge"] = self.data["xevBatteryActualStateOfCharge"]["value"]
                if (self.data["xevBatteryCapacity"] is not None and self.data["xevBatteryCapacity"]["value"] is not None):
                    elecs["Battery Capacity"] = self.data["xevBatteryCapacity"]["value"]
                if (self.data["xevBatteryChargeDisplayStatus"] is not None and self.data["xevBatteryChargeDisplayStatus"]["value"] is not None):
                    elecs["Battery Charge Display Status"] = self.data["xevBatteryChargeDisplayStatus"]["value"]
                if (self.data["xevBatteryChargerCurrentOutput"] is not None and self.data["xevBatteryChargerCurrentOutput"]["value"] is not None):
                    elecs["Battery Charger Current Output"] = self.data["xevBatteryChargerCurrentOutput"]["value"]
                if (self.data["xevBatteryChargerVoltageOutput"] is not None and self.data["xevBatteryChargerVoltageOutput"]["value"] is not None):
                    elecs["Battery Charger Voltage Output"] = self.data["xevBatteryChargerVoltageOutput"]["value"]
                if (self.data["Battery Energy Remaining"] is not None and self.data["xevBatteryEnergyRemaining"]["value"] is not None):
                    elecs["xevBatteryEnergyRemaining"] = self.data["xevBatteryEnergyRemaining"]["value"]
                if (self.data["xevBatteryIoCurrent"] is not None and self.data["xevBatteryIoCurrent"]["value"] is not None):
                    elecs["Battery Io Current"] = self.data["xevBatteryIoCurrent"]["value"]
                if (self.data["xevBatteryMaximumRange"] is not None and self.data["xevBatteryMaximumRange"]["value"] is not None):
                    elecs["Battery Max Range"] = self.data["xevBatteryMaximumRange"]["value"]
                if (self.data["xevBatteryPerformanceStatus"] is not None and self.data["xevBatteryPerformanceStatus"]["value"] is not None):
                    elecs["Battery Performance Status"] = self.data["xevBatteryPerformanceStatus"]["value"]
                if (self.data["xevBatteryRange"] is not None and self.data["xevBatteryRange"]["value"] is not None):
                    elecs["Battery Range"] = self.data["xevBatteryRange"]["value"]
                if (self.data["xevBatteryStateOfCharge"] is not None and self.data["xevBatteryStateOfCharge"]["value"] is not None):
                    elecs["Battery Fill Level"] = self.data["xevBatteryStateOfCharge"]["value"]
                if (self.data["xevBatteryTemperature"] is not None and self.data["xevBatteryTemperature"]["value"] is not None):
                    elecs["Battery Temperature"] = self.data["xevBatteryTemperature"]["value"]
                if (self.data["xevBatteryTimeToFullCharge"] is not None and self.data["xevBatteryTimeToFullCharge"]["value"] is not None):
                    elecs["Time to Full Charge"] = self.data["xevBatteryTimeToFullCharge"]["value"]
                if (self.data["xevBatteryVoltage"] is not None and self.data["xevBatteryVoltage"]["value"] is not None):
                    elecs["Battery Voltage"] = self.data["xevBatteryVoltage"]["value"]
                if (self.data["xevChargeStationCommunicationStatus"] is not None and self.data["xevChargeStationCommunicationStatus"]["value"] is not None):
                    elecs["Charger Status"] = self.data["xevChargeStationCommunicationStatus"]["value"]
                if (self.data["xevChargeStationPowerType"] is not None and self.data["xevChargeStationPowerType"]["value"] is not None):
                    elecs["Charger Power Type"] = self.data["xevChargeStationPowerType"]["value"]
                if (self.data["xevPlugChargerStatus"] is not None and self.data["xevPlugChargerStatus"]["value"] is not None):
                    elecs["Plug Status"] = self.data["xevPlugChargerStatus"]["value"]
                if (self.data["xevTractionMotorCurrent"] is not None and self.data["xevTractionMotorCurrent"]["value"] is not None):
                    elecs["Traction Motor Current"] = self.data["xevTractionMotorCurrent"]["value"]
                if (self.data["xevTractionMotorVoltage"] is not None and self.data["xevTractionMotorVoltage"]["value"] is not None):
                    elecs["Traction Motor Voltage"] = self.data["xevTractionMotorVoltage"]["value"]
                return elecs
```
well technically what i dumped in originally was even lazier than that.  this is the revised muckery. at first the names of every value was just the original names from the metrics returned by the API.  you can laugh at me cause I used powershell to parse your json and get the names then spit out python code in a loop. hahaha. yes i used powershell to make python. i'm THAT guy now. lol

**Comment by itchannel** [comment] 2023-10-12 03:57
haha I've done that with powershell before :)

Just a heads up new Beta 8 is out as I found a big bug which meant it wasn't updating data for some people unless the integration was restarted.

**Comment by mojomojoman** [comment] 2023-10-12 03:59
dude. i think i've been seeing that problem for like a year or so.  even joined a discussion someone else started about it but i think everyone thought we were nuts. that will be epic if you fixed that.

**Comment by itchannel** [comment] 2023-10-12 04:02
So this issue I introduced when recoding the API. Basically I set a variable on initialisation which contains all the data "self.data" but then that data is never updated again from the coordinator. Now it updates on every refresh. 

I'd be interested to hear more about this other issue you mention from before, I've never had the issue but certainly something I can look at if it's still a problem.

**Comment by mojomojoman** [comment] 2023-10-12 04:07
Well, simple really. I would make a change to the car (e.g. plugin the charger or open a door). I could see the change in the ford app. so i know the car refreshed with ford and the data was in the api. but nothing short of reloading the integration would get it to show in HA.  i would wait the polling period. i even tried kicking off the refresh function you had as a service but still the data in HA remained stagnant until a reload of the integration.    Now thats not entirely true though because if I walked away from the computer for a loong time and came back later eventually HA did update without my intervention. I never timed it or had the patience to diagnose it in great detail.  I made my "reload" button and smashed that when i was impatient. ;-)

**Comment by mojomojoman** [comment] 2023-10-12 04:36
Yeah sorry but i loaded up beta 8 and then went and opened the car door and unplugged the charger then came back and sat in front of HA for much longer than my polling period and I still dont see the changes.  Pretty certain if i hit that reload button i will but that's cheating right?  it still says the car is locked and doors closed and the charger is plugged in.

![image](https://github.com/itchannel/fordpass-ha/assets/67213346/92b1a510-d824-4b36-a338-58c6e51f803a)

now after reloaded... wait. no change at all. ok this is new.
let me run the Autonomic.py and check the json.

yep. it is. 
![image](https://github.com/itchannel/fordpass-ha/assets/67213346/f3b412d4-190c-4d74-8d73-fa9051a0dedf)

hmm. i'll try rebooting HA and see if that loads the fresh data but this might be a step backwards actually.

**Comment by itchannel** [comment] 2023-10-12 04:42
Can you check your HA logs for any errors? Also can you check the source code in sensor.py and make sure line 73 is this "self.data = self.coordinator.data["metrics"]" as it sounds like you were/still on the old version as that was the bug in Beta 7 where you'd have to reboot HA to get it updated

I've just tried it on mine and it updated on next refresh interval when I locked/unlocked my car.

**Comment by mojomojoman** [comment] 2023-10-12 04:43
sure. i also just noticed a bug in the doorStatus data reporting but let me check this first.

**Comment by mojomojoman** [comment] 2023-10-12 04:49
line 73:
`        self.data = self.coordinator.data["metrics"]`
nothing interesting in the logs. but lemme turn debugging on and let it sit for a while.

**Comment by mojomojoman** [comment] 2023-10-12 05:07
@itchannel  there's a LOT of debug data. like all the datas.  i can't sanitize it all and don't want to publicly post my token, VIN, lat/lon etc. so is there a way I can send it directly to you?

FYI, I closed the car door and locked it like 15 min ago but still dont see any change in HA.

**Comment by itchannel** [comment] 2023-10-12 05:45
Email github@itchannel.me is easiest :)

Weird it's not registering for you. Hoping your logs show me something.

**Comment by SquidBytes** [comment] 2023-10-12 14:24
> Yeah sorry but i loaded up beta 8 and then went and opened the car door and unplugged the charger then came back and sat in front of HA for much longer than my polling period and I still dont see the changes. Pretty certain if i hit that reload button i will but that's cheating right? it still says the car is locked and doors closed and the charger is plugged in.
> 
> ![image](https://user-images.githubusercontent.com/67213346/274481035-92b1a510-d824-4b36-a338-58c6e51f803a.png)
> 
> now after reloaded... wait. no change at all. ok this is new. let me run the Autonomic.py and check the json.
> 
> yep. it is. ![image](https://user-images.githubusercontent.com/67213346/274481844-f3b412d4-190c-4d74-8d73-fa9051a0dedf.png)
> 
> hmm. i'll try rebooting HA and see if that loads the fresh data but this might be a step backwards actually.
> 
> update: yes, after rebooting HA I see the car unlocked and doors open and charge plug status as "DISCONNECTED" now.

Your HA Card is beautiful, I'm jealous

**Comment by mojomojoman** [comment] 2023-10-12 16:22
> Your HA Card is beautiful, I'm jealous

I can take almost no credit for that. Some guy on the forums did this. He made SVGs of his Mazda which looks enough like my Ford so I used it.  Its actually cooler than you think. When you have a door open it shows as open and glows in red.  I just grabbed his SVG files and code and changed the entities and added some more labels here and there. I've always wanted to make the windows do something to show as open too but I didn't have the patience to learn how to use the tool he used to do the SVGs.

**Comment by mojomojoman** [comment] 2023-10-12 16:40
> Email [github@itchannel.me](mailto:github@itchannel.me) is easiest :)
> 
> Weird it's not registering for you. Hoping your logs show me something.

sent

**Comment by SquidBytes** [comment] 2023-10-12 16:59
> > Your HA Card is beautiful, I'm jealous
> 
> I can take almost no credit for that. Some guy on the forums did this. He made SVGs of his Mazda which looks enough like my Ford so I used it. Its actually cooler than you think. When you have a door open it shows as open and glows in red. I just grabbed his SVG files and code and changed the entities and added some more labels here and there. I've always wanted to make the windows do something to show as open too but I didn't have the patience to learn how to use the tool he used to do the SVGs.

If you're able to, and don't mind sharing, I'd love to do something similar. If you could send me the things that would be awesome.
SquidBytes@pm.me

**Comment by nytram-md** [comment] 2023-10-13 06:24
Ford Focus 21 Model UK Diesel Manual

Im running latest 1.54 Release 2

I added the utility meters and they were working until the API change, They are looking for the speed_odometer but that doesnt seem to exist any more. Does anyone know where the mileage is now please ?

Is this what I should expect or is the app not responding as you would expect as I have 2 sensors not pulling anything as you can see fordpass_dieselSystemStatus and fordpass_exhaustFluidLevel

![image](https://github.com/itchannel/fordpass-ha/assets/55548608/bb2f1420-4df4-489a-b667-7cc207b15272)
![image](https://github.com/itchannel/fordpass-ha/assets/55548608/d5b96d62-9290-417e-ba69-10f20a582f38)

`Logger: homeassistant.components.sensor
Source: helpers/entity_platform.py:507
Integration: Sensor (documentation, issues)
First occurred: 12 October 2023 at 21:06:44 (1 occurrences)
Last logged: 12 October 2023 at 21:06:44

Error adding entities for domain sensor with platform fordpass
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 507, in async_add_entities
    await asyncio.gather(*tasks)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 752, in _async_add_entity
    await entity.add_to_platform_finish()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1057, in add_to_platform_finish
    self.async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 779, in async_write_ha_state
    self._async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 879, in _async_write_ha_state
    state, attr = self._async_generate_attributes()
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 823, in _async_generate_attributes
    attr.update(self.extra_state_attributes or {})
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/fordpass/sensor.py", line 527, in extra_state_attributes
    return self.get_value("attribute")
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/fordpass/sensor.py", line 484, in get_value
    if "dieselExhaustOverTemp" in self.data["indicators"]:
                                  ~~~~~~~~~^^^^^^^^^^^^^^
KeyError: 'indicators'
`

`Logger: homeassistant.components.sensor
Source: helpers/entity_platform.py:367
Integration: Sensor (documentation, issues)
First occurred: 12 October 2023 at 21:06:44 (1 occurrences)
Last logged: 12 October 2023 at 21:06:44

Error while setting up fordpass platform for sensor
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 367, in _async_setup_platform
    await asyncio.gather(*pending)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 507, in async_add_entities
    await asyncio.gather(*tasks)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 752, in _async_add_entity
    await entity.add_to_platform_finish()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1057, in add_to_platform_finish
    self.async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 779, in async_write_ha_state
    self._async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 879, in _async_write_ha_state
    state, attr = self._async_generate_attributes()
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 823, in _async_generate_attributes
    attr.update(self.extra_state_attributes or {})
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/fordpass/sensor.py", line 527, in extra_state_attributes
    return self.get_value("attribute")
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/fordpass/sensor.py", line 484, in get_value
    if "dieselExhaustOverTemp" in self.data["indicators"]:
                                  ~~~~~~~~~^^^^^^^^^^^^^^
KeyError: 'indicators'
`
`Logger: homeassistant.components.sensor
Source: helpers/entity_platform.py:573
Integration: Sensor (documentation, issues)
First occurred: 12 October 2023 at 21:06:47 (1 occurrences)
Last logged: 12 October 2023 at 21:06:47

fordpass: Error on device update!
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 573, in _async_add_entity
    await entity.async_device_update(warning=False)
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 991, in async_device_update
    await self.async_update()
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 507, in async_update
    await self.coordinator.async_request_refresh()
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 240, in async_request_refresh
    await self._debounced_refresh.async_call()
  File "/usr/src/homeassistant/homeassistant/helpers/debounce.py", line 93, in async_call
    await task
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 266, in async_refresh
    await self._async_refresh(log_failures=True)
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 389, in _async_refresh
    self.async_update_listeners()
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 172, in async_update_listeners
    update_callback()
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 469, in _handle_coordinator_update
    self.async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 779, in async_write_ha_state
    self._async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 879, in _async_write_ha_state
    state, attr = self._async_generate_attributes()
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 823, in _async_generate_attributes
    attr.update(self.extra_state_attributes or {})
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/fordpass/sensor.py", line 527, in extra_state_attributes
    return self.get_value("attribute")
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/fordpass/sensor.py", line 484, in get_value
    if "dieselExhaustOverTemp" in self.data["indicators"]:
                                  ~~~~~~~~~^^^^^^^^^^^^^^
KeyError: 'indicators'
`

`This error originated from a custom integration.

Logger: homeassistant
Source: custom_components/fordpass/sensor.py:484
Integration: FordPass (documentation, issues)
First occurred: 12 October 2023 at 21:21:53 (40 occurrences)
Last logged: 07:10:30

Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 233, in _handle_refresh_interval
    await self._async_refresh(log_failures=True, scheduled=True)
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 389, in _async_refresh
    self.async_update_listeners()
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 172, in async_update_listeners
    update_callback()
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 469, in _handle_coordinator_update
    self.async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 779, in async_write_ha_state
    self._async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 879, in _async_write_ha_state
    state, attr = self._async_generate_attributes()
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 823, in _async_generate_attributes
    attr.update(self.extra_state_attributes or {})
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/fordpass/sensor.py", line 527, in extra_state_attributes
    return self.get_value("attribute")
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/fordpass/sensor.py", line 484, in get_value
    if "dieselExhaustOverTemp" in self.data["indicators"]:
                                  ~~~~~~~~~^^^^^^^^^^^^^^
KeyError: 'indicators'
`

Hope this helps

**Comment by SquidBytes** [comment] 2023-10-13 23:27
@ziptbm I would be curious to know if you're still seeing this on 1.57
If so, more jsons would be greatly appreciated and I can look into it and maybe get it in 1.58

**Comment by itchannel** [comment] 2023-10-19 10:02
Can I get confirmation this is all working for people in 1.58?

**Comment by SquidBytes** [comment] 2023-10-19 14:52
For Range, we are just grabbing the value returned form the API - and then converting it if needed.
![image](https://github.com/itchannel/fordpass-ha/assets/145411069/7cec8330-fba0-4d4d-97b7-4731f9ae86bb)

My guess on the minor differences is the FordPass App is updated immediately - or on refresh, and they might be rounding down out of an abundance of caution. HA is using the recent data from the last request and displaying with decimal points.

If there are differences between different HA sensors with State of Charge - then I may have mapped a sensor incorrectly. In the API there is both `xevBatteryStateOfCharge` and `xevBatteryActualStateOfCharge`. We are returning both in difference places, but it should be clear which one is which.

**Comment by SquidBytes** [comment] 2023-10-26 02:11
This has also now changed over to using HomeAssistant for conversions. They should now be very similar and I wouldn't expect any major differences.

**Comment by SquidBytes** [comment] 2023-10-30 20:06
I'm going to close this as I believe the issues have migrated over to new issues - or been resolved.
Feel free to re-open if I am incorrect.

**Closed by SquidBytes** 2023-10-30 20:06 UTC
