### ISSUE TITLE
Failed setup, will retry Issue

### ISSUE THREAD

**Issue by BobMac57** [itchannel/fordpass-ha#499] opened 2024-05-17 21:10 UTC
Erratic issues past few days and getting error 'Failed setup, will retry' and even went as far as resetting my password on Ford and the FordPass app. Appears we are getting blocked....

**Comment by danielbrunt57** [comment] 2024-05-17 22:03
Same here for me...
![image](https://github.com/itchannel/fordpass-ha/assets/49846893/97ed0c35-90e6-4bbc-be23-d002ff1d7845)

**Comment by cryptk** [comment] 2024-05-17 22:11
Probably a duplicate of #488

**Comment by aminorjourney** [comment] 2024-05-18 03:40
Agreed - Note that the codebase currently has a hard-coded alternative for the login end point - it may have been closed by Ford.

**Comment by rambaldi014** [comment] 2024-05-20 18:59
Same in Europe.
Can't login. Is there a fix in process?
![grafik](https://github.com/itchannel/fordpass-ha/assets/104066513/a4b5d691-cccd-4b12-bedd-c9ed304276ad)

**Comment by danantonson** [comment] 2024-05-26 17:14
Same issue here.  Can't login anymore.

**Comment by marcokreeft87** [comment] 2024-05-26 19:53
Same :(

**Comment by someevil** [comment] 2024-05-27 13:24
I see there is v1.70 released yesterday, it is not detected when I try to install on HA via HACS. I have never tried manually installing something on my HA yet, but I just downloaded the ZIP for v 1.70, anyone able to tell me how to load this zip into my HA on Raspberry Pi? Surely it cannot be too difficult? (famous last words!)

**Comment by noman1228** [comment] 2024-05-27 22:21
In HA
DEVELOPER TOOLS-> SERVICES->

service: update.install
Target entity: update.fordpass_update
Version: 1.70

**Comment by BobMac57** [comment] 2024-05-30 08:26
As of yesterday, it is working again and I'm still on 1.68...

**Comment by thewolfman56** [comment] 2024-05-30 16:22
Not working for me on 1.68

**Comment by BobMac57** [comment] 2024-05-30 18:55
Ugh, just saw this and now mines not working again. This is nuts...

**Comment by marcokreeft87** [comment] 2024-05-31 16:10
Why is it closed?

**Comment by SquidBytes** [comment] 2024-05-31 16:14
Apologies, it is probably best to have this as a separate issue.
I was guessing this is related to #488

**Comment by SquidBytes** [comment] 2024-05-31 16:59
Is this issue specifically on build 1.68 from HACS?

[There was this temp fix by replacing the `fordpass_new.py` code with the code from 1.69](https://github.com/itchannel/fordpass-ha/issues/488#issuecomment-2129164642).

Its probably best to copy your token file prior to a restart of HA.
I don't remember if this fix was the issue with tokens being removed or not. There has been many things going on.
However, I believe that modifying 1.68 release with the `fordpass_new.py` from 1.69 is working.

**Comment by BobMac57** [comment] 2024-05-31 22:18
> Is this issue specifically on build 1.68 from HACS?
> 
> [There was this temp fix by replacing the `fordpass_new.py` code with the code from 1.69](https://github.com/itchannel/fordpass-ha/issues/488#issuecomment-2129164642).
> 
> Its probably best to copy your token file prior to a restart of HA. I don't remember if this fix was the issue with tokens being removed or not. There has been many things going on. However, I believe that modifying 1.68 release with the `fordpass_new.py` from 1.69 is working.

 I didn't copy the token and instead copied the raw code and pasted/saved the file in HA, restarted and it is now working so far...

**Closed** 2024-12-18 22:43 UTC
Labels: bug
