### ISSUE TITLE
Fordpass Integration Loses Connection After ~48hrs

### ISSUE THREAD

**Issue by austinbeam** [itchannel/fordpass-ha#98] opened 2021-04-13 06:01 UTC
After configuring the integration, it works flawlessly connecting to two vehicles on the same account for the first ~48hrs or so. After this, it stops communicating and the entities become unavailable. This has happened twice now. The first time, I deleted the fordpass_token.txt and re-added the vehicles and was able to get it working again.

It's anyone else experiencing something similar? Something I'm doing wrong?

Here are some log outputs if it is helpful (VINs replaced with placeholders):

```
Logger: custom_components.fordpass
Source: custom_components/fordpass/__init__.py:162
Integration: FordPass (documentation, issues)
First occurred: April 8, 2021, 11:14:40 PM (2292 occurrences)
Last logged: 12:46:53 AM

Error communicating with FordPass for VIN1
Error communicating with FordPass for VIN2
```

```
Logger: custom_components.fordpass
Source: custom_components/fordpass/__init__.py:161
Integration: FordPass (documentation, issues)
First occurred: April 8, 2021, 11:14:40 PM (2292 occurrences)
Last logged: 12:46:53 AM

HTTPSConnectionPool(host='usapi.cv.ford.com', port=443): Max retries exceeded with url: /api/vehicles/v4/VIN2/status?lrdt=01-01-1970+00%3A00%3A00 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x6073bb50>: Failed to establish a new connection: [Errno -3] Try again'))
HTTPSConnectionPool(host='usapi.cv.ford.com', port=443): Max retries exceeded with url: /api/vehicles/v4/VIN1/status?lrdt=01-01-1970+00%3A00%3A00 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x60bce580>: Failed to establish a new connection: [Errno -3] Try again'))
HTTPSConnectionPool(host='usapi.cv.ford.com', port=443): Max retries exceeded with url: /api/vehicles/v4/VIN2/status?lrdt=01-01-1970+00%3A00%3A00 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x60c38dd8>: Failed to establish a new connection: [Errno -3] Try again'))
HTTPSConnectionPool(host='usapi.cv.ford.com', port=443): Max retries exceeded with url: /api/vehicles/v4/VIN2/status?lrdt=01-01-1970+00%3A00%3A00 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x5f1ae880>: Failed to establish a new connection: [Errno -3] Try again'))
Extra data: line 1 column 2738 (char 2737)
```

**Comment by itchannel** [comment] 2021-04-13 22:16
I've seen this error on HA docker instances where the DNS can't resolve the subdomain intermittently. Can you turn on debugging by adding this to your configuration then send me the complete log. 

```
logger:
  default: warning
  logs:
    custom_components.fordpass: debug
```

**Comment by austinbeam** [comment] 2021-04-14 03:43
Thanks for your help @itchannel and all your hard work on this.

Log attached, left it running for a while (~2.5hrs) and it just kept cycling this same thing over and over. Haven't seen the max retries error above show up this time around, but am consistently seeing the "Extra data" warning. I did notice that the first error takes ~14s whereas it almost immediately errors on subsequent tries.

Let me know if there's anything you'd like me to try next, I'll leave it as-is for now until you tell me otherwise.

[2021-04-13 Home Assistant Fordpass Log.txt](https://github.com/itchannel/fordpass-ha/files/6308036/2021-04-13.Home.Assistant.Fordpass.Log.txt)

**Comment by austinbeam** [comment] 2021-04-20 14:45
Any feedback on this @itchannel? Thanks again for your help.

**Comment by itchannel** [comment] 2021-04-26 08:04
Sorry been away so only just had a chance to check in. 

Would you be able to check to see if the fordpass_token.txt file changes at all from when you setup to start experiencing the error. I am going to add two cars to my test instance and let it run for 48hrs to see if I experience the same issue. However I can't see in your log the same error you experienced about being unable to resolve "usapi.cv.ford.com", are you still getting that error as well?

**Comment by austinbeam** [comment] 2021-04-27 04:12
Thanks for the feedback @itchannel. I went ahead an set them up again and they are immediately working. I took a snapshot of the fordpass_token.txt before and compared it to what was generated after.

It looks like the version that was there (i.e. not working) had a 'null' UserProfile, which is fully populated in the new (i.e. working) file. I can check again once it stops working again, but thought this is likely the same data point.

I do not appear to be getting the other error now.

**Comment by itchannel** [comment] 2021-04-28 23:21
Glad it's now working, good to know about the userProfile bit may need to add some more error checking if other people get it.

**Comment by austinbeam** [comment] 2021-04-29 02:58
Stopped working on me about 15:16 today. Log attached.

[2021-04-28_ha_log.txt](https://github.com/itchannel/fordpass-ha/files/6396053/2021-04-28_ha_log.txt)

As previously, the UserProfile in the token has gone null. I also noticed that there is an extra trailing brace (}) in the broken token file (i.e. it is not valid JSON when I open it up). This happened before as well, but I glazed over it. Now I'm noticing that this extra character lines up with the error in the log ("Extra data: line 1 column 2738"). Not sure if this is cause or effect (seems more likely the latter), but thought I'd point it out.

**Comment by mayermd** [comment] 2021-05-10 14:37
Wanted to jump in here and confirm the behavior.  I also went into the fordpass_token.txt and deleted the last } in the file and the integration started working again.

**Comment by itchannel** [comment] 2021-05-18 07:12
Ok thanks guys. Will add in some error checking and see why the extra brace is becoming a thing. Unfortunately I've been so busy it's finding the time to maintain this repo :)

**Comment by cmlittle** [comment] 2021-06-06 02:30
I've been experiencing this issue as well. Deleting the extra trailing brace fixes the issue temporarily for me, so it seems this is the cause, not the effect. I am running my instance in Docker.

**Comment by Trentmclaughlin** [comment] 2021-06-07 12:41
I have the same issue. I delete the token file, reboot, and it works for a short while.

**Comment by itchannel** [comment] 2021-06-09 01:10
Out of interest do you both have more than 1 car. I have now managed to reproduce this issue by adding another car to my account, so will be fixing asap :)

**Comment by serlinGi** [comment] 2021-06-09 06:15
hi, I confirm the problem occurs again if the second car is added.  for all the time that I left only one car, it didn't happen when adding the second one happened, and this already 2 times after 2 months

**Comment by itchannel** [comment] 2021-06-09 08:46
@serlinGi I have a fix for it coming in the next day or so. Been running 2 cars now for 24hrs without any issues. Good to see its the same issu

**Comment by itchannel** [comment] 2021-06-09 08:47
Should be a fix for this in 1.16 in the next couple of days. Just running it on my instance now and has been 24hrs without an error running 2 cars.

**Comment by serlinGi** [comment] 2021-06-09 09:03
meanwhile, thank you for your work.  if it can be useful I tell you that I have removed the final "}" bracket for 27 hours and for the moment it is still working fine.

**Comment by Trentmclaughlin** [comment] 2021-06-09 12:51
Yes, two vehicles here as well. Thanks for working on this.

**Comment by itchannel** [comment] 2021-06-10 00:08
I've currently got a hacky workaround in the code which if it fails to read the json it removes the extra bracket. Not the nicest way but it works for now. Don't know whether to release this as a temporary fix or keep working on something more intelligent. Downside is waiting for the token to expire each time :)

**Comment by serlinGi** [comment] 2021-06-10 06:22
at the moment I comfortably exceeded 48 hours.  if it continues to work, in another 12 hours I will try to do a restart of HA to understand at what moment the token is compromised by the bracket

**Comment by itchannel** [comment] 2021-06-10 06:26
So the problem is caused by the integration running twice (per car) and trying to update the token file at the same time. Sometimes it clashes and results in a slightly corrupted file (extra bracket etc). I was trying to see if there was a way to see if an existing sync job was running and to wait until it was finished but HA documentation is letting me down. 

Fix I'm now testing is when the file becomes corrupt it reruns the auth() routing thus creating a new token file and fixing it without relying on manually deleting anything. Going to leave it running on my dev and prod instances for 48hrs to see if it resolves the issue fully.

**Comment by itchannel** [comment] 2021-06-10 06:27
Open to suggestions if anyone knows a better way

**Comment by serlinGi** [comment] 2021-06-12 16:35
hi,
I would say it is working fine.  
no problem days later.
and even after updating the Core and OS to the new versions, with the consequent restart and reboot I'm having problems.  
all perfect for the moment 🤞😉

**Comment by itchannel** [comment] 2021-06-13 00:32
I've just release #102 which adds in a check for a malformed token and reauths the API. I have noticed sometimes it can be days before it gets malformed or just hours, so this check at least fixes that issue now and has been running for 48hrs+ for me with multiple restarts and checks 👍

**Comment by austinbeam** [comment] 2021-06-13 00:38
Awesome, thanks @itchannel!

**Comment by itchannel** [comment] 2021-06-16 23:39
I've been running the latest version now for a week without any drop outs and 2 vehicles so going to mark this as closed for now .

**Closed by itchannel** 2021-06-16 23:39 UTC

**Comment by austinbeam** [comment] 2021-06-17 00:55
Working great for me as well, thanks again!
