### ISSUE TITLE
Creditals not working after reinstalling integration

### ISSUE THREAD

**Issue by benmartucci** [itchannel/fordpass-ha#501] opened 2024-05-20 06:04 UTC
I have had this integration running for about 2 years, after it stopped updating the sensors I tried to reinstall the integration but now it says my credentials are incorrect, which they are not. I am using the US server.

**Comment by wriel1989** [comment] 2024-05-21 09:14
Its known that the api has been changed and this effects the use of the integration. We need to wait it is fixed and working whit the new api from ford.

**Comment by ThirteenTX** [comment] 2024-05-21 12:53
It has to do with this issue #488

**Comment by 951ryan** [comment] 2024-05-24 22:24
Super easy fix, simply replace the contents of fordpass_new.py with the contents below and restart HA, boom working again (for now at least).

https://github.com/itchannel/fordpass-ha/blob/1.69/custom_components/fordpass/fordpass_new.py

**Comment by advisorgee** [comment] 2024-05-25 00:02
@951ryan thanks for the tip. worked perfectly

**Comment by itchannel** [comment] 2024-05-25 00:27
Going to close this issue as it's a duplicate of the main thread #488 

If you already have the integration installed and just disabled then there is a fix as @951ryan pointed out which should work as long as you still have your token file :)

**Closed by itchannel** 2024-05-25 00:27 UTC
