### ISSUE TITLE
Unable to login - Australia

### ISSUE THREAD

**Issue by OppyLock** [itchannel/fordpass-ha#432] opened 2023-11-13 22:38 UTC
Not sure if this is specific to me, Australia or luck ...

Vehicle had a software update yesterday and due to its master reset I had to reactivate it on fordpass.  Fordpass works fine.
I then removed and readded the integration but it always fails with 'Invalid Credentials'.  Credentials are fine.  I even did a password change to see if that may help, but no.
I have also removed the integration from HA and also from HACS and reloaded to no avail with OS reboots between each step just to be sure.

From the logs:
2023-11-14 09:21:12.455 DEBUG (MainThread) [custom_components.fordpass.config_flow] Australia
2023-11-14 09:21:12.455 DEBUG (MainThread) [custom_components.fordpass.fordpass_new] /config/custom_components/fordpass/my@email.com_fordpass_token.txt
2023-11-14 09:21:12.456 DEBUG (SyncWorker_0) [custom_components.fordpass.fordpass_new] New System
2023-11-14 09:21:12.456 DEBUG (SyncWorker_0) [custom_components.fordpass.fordpass_new] 0
2023-11-14 09:21:12.456 DEBUG (SyncWorker_0) [custom_components.fordpass.fordpass_new] Running Step1
2023-11-14 09:21:13.684 DEBUG (SyncWorker_0) [custom_components.fordpass.fordpass_new] Incorrect response from URL
2023-11-14 09:21:13.684 DEBUG (SyncWorker_0) [custom_components.fordpass.fordpass_new] Step 1 Exception
2023-11-14 09:21:13.684 DEBUG (SyncWorker_0) [custom_components.fordpass.fordpass_new] Response from URL was invalid
2023-11-14 09:21:13.684 DEBUG (SyncWorker_0) [custom_components.fordpass.fordpass_new] New System
2023-11-14 09:21:13.684 DEBUG (SyncWorker_0) [custom_components.fordpass.fordpass_new] 1
2023-11-14 09:21:13.684 DEBUG (SyncWorker_0) [custom_components.fordpass.fordpass_new] Running Step1
2023-11-14 09:21:13.975 DEBUG (SyncWorker_0) [custom_components.fordpass.fordpass_new] Incorrect response from URL
2023-11-14 09:21:13.975 DEBUG (SyncWorker_0) [custom_components.fordpass.fordpass_new] Step 1 Exception
2023-11-14 09:21:13.975 DEBUG (SyncWorker_0) [custom_components.fordpass.fordpass_new] Response from URL was invalid
...
2023-11-14 09:21:16.165 DEBUG (SyncWorker_0) [custom_components.fordpass.fordpass_new] New System
2023-11-14 09:21:16.165 DEBUG (SyncWorker_0) [custom_components.fordpass.fordpass_new] 10
2023-11-14 09:21:16.165 DEBUG (SyncWorker_0) [custom_components.fordpass.fordpass_new] Running Step1
2023-11-14 09:21:16.443 DEBUG (SyncWorker_0) [custom_components.fordpass.fordpass_new] Incorrect response from URL
2023-11-14 09:21:16.443 DEBUG (SyncWorker_0) [custom_components.fordpass.fordpass_new] Step 1 Exception
2023-11-14 09:21:16.443 DEBUG (SyncWorker_0) [custom_components.fordpass.fordpass_new] Response from URL was invalid

**Comment by firstandlast1966** [comment] 2023-11-13 22:44
Hi, I just restarted HA and saw the Fordpass integration had failed to load. I deleted it and tried to set it up again with my credentials and got the error "invalid credentials". I'm based in UK.

**Comment by OppyLock** [comment] 2023-11-13 22:45
Fords tinkering continues ... so nice to see they treat the customer base as 'test' instead of 'production'

**Comment by luongdaniel** [comment] 2023-11-13 22:49
I am also having this problem, also in Australia.

**Comment by frankie-boy-hgv** [comment] 2023-11-13 22:55
Some here in the Netherlands

**Comment by benk016** [comment] 2023-11-13 23:12
Same here in USA. 

2023-11-13 16:59:00.972 DEBUG (SyncWorker_4) [custom_components.fordpass.fordpass_new] Getting Vehicle Status
2023-11-13 16:59:00.972 DEBUG (SyncWorker_4) [custom_components.fordpass.fordpass_new] Fetching token
2023-11-13 16:59:00.973 DEBUG (SyncWorker_4) [custom_components.fordpass.fordpass_new] AUTO token not set in file
2023-11-13 16:59:00.973 DEBUG (SyncWorker_4) [custom_components.fordpass.fordpass_new] None
2023-11-13 16:59:00.973 DEBUG (SyncWorker_4) [custom_components.fordpass.fordpass_new] None
2023-11-13 16:59:00.973 DEBUG (SyncWorker_4) [custom_components.fordpass.fordpass_new] New System
2023-11-13 16:59:00.973 DEBUG (SyncWorker_4) [custom_components.fordpass.fordpass_new] 0
2023-11-13 16:59:00.973 DEBUG (SyncWorker_4) [custom_components.fordpass.fordpass_new] Running Step1
2023-11-13 16:59:01.162 DEBUG (SyncWorker_4) [custom_components.fordpass.fordpass_new] Incorrect response from URL
2023-11-13 16:59:01.162 DEBUG (SyncWorker_4) [custom_components.fordpass.fordpass_new] Step 1 Exception
2023-11-13 16:59:01.163 DEBUG (SyncWorker_4) [custom_components.fordpass.fordpass_new] Response from URL was invalid
2023-11-13 16:59:01.163 DEBUG (SyncWorker_4) [custom_components.fordpass.fordpass_new] New System
2023-11-13 16:59:01.163 DEBUG (SyncWorker_4) [custom_components.fordpass.fordpass_new] 1
2023-11-13 16:59:01.163 DEBUG (SyncWorker_4) [custom_components.fordpass.fordpass_new] Running Step1
2023-11-13 16:59:01.250 DEBUG (SyncWorker_4) [custom_components.fordpass.fordpass_new] Incorrect response from URL
2023-11-13 16:59:01.251 DEBUG (SyncWorker_4) [custom_components.fordpass.fordpass_new] Step 1 Exception
2023-11-13 16:59:01.251 DEBUG (SyncWorker_4) [custom_components.fordpass.fordpass_new] Response from URL was invalid
2023-11-13 16:59:01.251 DEBUG (SyncWorker_4) [custom_components.fordpass.fordpass_new] New System
2023-11-13 16:59:01.251 DEBUG (SyncWorker_4) [custom_components.fordpass.fordpass_new] 2

**Comment by serlinGi** [comment] 2023-11-13 23:56
same here - Italy

**Comment by jwinston100** [comment] 2023-11-13 23:57
Same here USA

**Comment by itchannel** [comment] 2023-11-14 00:05
The client identifier has been changed for step1 of the login. I'll need to work out what the client identifier has now been changed to which might take a bit of time. I recommend disabling the integration for now until I can make this code change.

**Comment by itchannel** [comment] 2023-11-14 00:34
So I can't even make the normal Fordpass App work. So going to go with this being a technical glitch on their side. But will monitor closely :)

**Comment by jwinston100** [comment] 2023-11-14 00:52
My Fordpass app does work, and everything updates accurately in the app, but the Home Assistant integration is not working.

**Comment by itchannel** [comment] 2023-11-14 00:55
@jwinston100 I'm going to guess you have the latest version of the application. The new version uses a completely different authentication flow via Azure Front door rather than the old way of using IBM access. 

It needs a considerable rewrite to make it work with the new login flow.

**Comment by jwinston100** [comment] 2023-11-14 01:18
@itchannel My Fordpass app is Android version 4.31.0, last updated October 20, 2023. Sorry the dicks at Ford mucked around with the authentication flow, and thanks for all the work you do.

**Comment by serlinGi** [comment] 2023-11-14 07:39
> Quindi non riesco nemmeno a far funzionare la normale app Fordpass. Quindi accetteremo che si tratti di un problema tecnico dalla loro parte. Ma monitorerò attentamente :)
> 
> È interessante notare che la nuova versione dell'app utilizza un accesso diverso, potrebbe essere divertente eseguire il debug.

**Comment by serlinGi** [comment] 2023-11-14 07:40
I don't understand if you also have difficulties with the Fordpass app.  I confirm that for my 2 cars the app works correctly while the integration is not possible

**Comment by itchannel** [comment] 2023-11-14 07:45
The current status is that Ford have changed the way the application logs in to their API. It looks like this change was made within the last month so if you have a recent version of the Fordpass app you can login fine. However this integration and older versions of the application used the old login system and it appears as of today they have switched across fully to the new system which is why this has stopped working. 

I will need to work out the new structure and redo the integration to use the new login.

**Comment by itchannel** [comment] 2023-11-14 10:27
![image](https://github.com/itchannel/fordpass-ha/assets/5840973/91ad882a-6351-45b0-ad1b-96b0233fb9a2)

Good news I have made progress and have it working again. However I need to refactor and sort my code as currently there is 0 error handling.

**Comment by frankie-boy-hgv** [comment] 2023-11-14 10:30
> ![image](https://user-images.githubusercontent.com/5840973/282744143-91ad882a-6351-45b0-ad1b-96b0233fb9a2.png)
> 
> Good news I have made progress and have it working again. However I need to refactor and sort my code as currently there is 0 error handling.

That was fast. Will you release it in an alpha or beta? Or is it too soon for that :-)?

**Comment by itchannel** [comment] 2023-11-14 10:42
I will bring out a Beta hopefully tonight for brave people to test. But it won't have full error checking and obviously I haven't checked all features like token timeouts yet.

**Comment by frankie-boy-hgv** [comment] 2023-11-14 10:43
> I will bring out a Beta hopefully tonight for brave people to test. But it won't have full error checking and obviously I haven't checked all features like token timeouts yet.

Awesome!
No worries, will test it for you :-)

**Comment by itchannel** [comment] 2023-11-14 11:06
> > I will bring out a Beta hopefully tonight for brave people to test. But it won't have full error checking and obviously I haven't checked all features like token timeouts yet.
> 
> Awesome! No worries, will test it for you :-)

If you want a play I've pushed 1.63 Beta 1. I'm running it on my HA instance but be aware there's probably going to be bugs :)

**Comment by serlinGi** [comment] 2023-11-14 11:14
I just started the Beta update;  I will let you know.  thanks for everything

**Comment by serlinGi** [comment] 2023-11-14 11:38
and I can confirm that at the moment, without having yet interacted with the car, everything seems to work perfectly: access without problems and sensors all correctly valorised.
THX

**Comment by frankie-boy-hgv** [comment] 2023-11-14 11:44
> > > I will bring out a Beta hopefully tonight for brave people to test. But it won't have full error checking and obviously I haven't checked all features like token timeouts yet.
> > 
> > 
> > Awesome! No worries, will test it for you :-)
> 
> If you want a play I've pushed 1.63 Beta 1. I'm running it on my HA instance but be aware there's probably going to be bugs :)

So far so good  👍.

**Comment by itchannel** [comment] 2023-11-14 11:50
I know of a couple of bugs that I need to fix as I've accidentally hardcoded some region strings but otherwise sounds like it's working for people so far 👍

**Comment by CapMousse** [comment] 2023-11-14 13:16
> > > I will bring out a Beta hopefully tonight for brave people to test. But it won't have full error checking and obviously I haven't checked all features like token timeouts yet.
> > 
> > 
> > Awesome! No worries, will test it for you :-)
> 
> If you want a play I've pushed 1.63 Beta 1. I'm running it on my HA instance but be aware there's probably going to be bugs :)

FYI, this beta seems to work really well on my end :)

**Comment by benk016** [comment] 2023-11-14 13:30
Just installed the beta and everything came right back as expected.

**Comment by slopemad** [comment] 2023-11-14 13:34
Beta is installed and working fine. UK.

**Comment by OppyLock** [comment] 2023-11-14 21:53
... and Australia working again. :)  TYVM We all appreciate your work.

**Comment by itchannel** [comment] 2023-11-26 09:22
1.63 is now officially released. So going to close this issue. If anyone is having further problems please open a separate issue so I can keep track.

**Closed by itchannel** 2023-11-26 09:22 UTC
