### ISSUE TITLE
sensor.fordpass_indicators

### ISSUE THREAD

**Issue by michaeltryl** [itchannel/fordpass-ha#455] opened 2023-12-09 20:26 UTC
Hi
I can't figure out how to use "sensor.fordpass_indicators" in automations.
For example, when LowWasherFluid If true, I would like a message, but
{{state_attr('sensor.fordpass_indicators','LowWasherFluid')}}
Just gives me "null", so how can I use it in a condition in an automation

**Comment by J-shw** [comment] 2023-12-10 06:09
Use - {{state_attr('sensor.fordpass_indicators','lowWasherFluid')}}

**Comment by michaeltryl** [comment] 2023-12-10 10:21
Thanks, so the first letter has to be lower case?

**Comment by cryptk** [comment] 2023-12-12 21:19
The attribute name actually does have a lowercase letter as the first letter. The problem is that the home assistant UI under integrations tries to be helpful and normalize text. If you look at the sensor under Developer Tools > States you can see the unmodified names of the attributes with their initial letter being lowercase.

**Comment by itchannel** [comment] 2023-12-30 00:27
Closing as @cryptk has answered the query.

**Closed by itchannel** 2023-12-30 00:27 UTC
