### ISSUE TITLE
Poll API Service not working?

### ISSUE THREAD

**Issue by pbryan7** [itchannel/fordpass-ha#368] opened 2023-10-15 03:06 UTC
It seems the Poll API service isn't working with 1.57.    

I was hoping to use it in an Automation as a temporary solution to the repeated "unavailable" errors.   But it doesn't seem to actually re-poll the API anymore.  In the debug log it seems to do something, but doesn't actually update any sensors, and no errors or warnings are produced.

**Comment by itchannel** [comment] 2023-10-15 03:18
The poll service does work. However the current "unavailable" issue messes up the tokens which only a restart of HA fixes.

I should be pushing a temporary fix in a few hours, I'm still debugging at the moment to come up with a more permanent fix for handling the API going offline a lot.

**Comment by dtx1990** [comment] 2023-10-15 05:51
I noticed that the problem is mainly caused by the original Ford app on my Android device, last updated 22 hours ago

**Comment by AlexW75** [comment] 2023-10-16 15:31
Have a simmilar problem - it seems that the update is not working.
Even when I force an update it will not be done.

**Comment by lpersoons** [comment] 2023-10-17 17:40
I have a similar problem, integration is not updating anymore and set-up of the integration is not successful.

**Comment by hvorragend** [comment] 2023-10-19 13:56
> 1.58 is now out so give that a go.
> 
> Also for context "poll_api" just refreshes data from the api, "refresh_status" will actively interrogate the car to get the latest information.

And does "refresh_status" include the "poll_api"? Yes, isn't it?

**Comment by itchannel** [comment] 2023-10-19 21:02
> Sorry for hijacking the thread. Does it make sense to poll_api frequently without refreshing the status? Do we know the strategy of sending data by CAR to Ford? Is it always on demand, or it may send data more often than usual (ie when driving)?
> 
> For example, after locking the car API still reports doors open (ajar of some). It requires to call refresh to update the door status. What's the point of using poll_api alone then?

The reason for adding poll_api was for the exact use case you mentioned. Mainly for people to test if data is refreshed more often from the car when driving the vehicle etc. It was asked for by a couple of users so is only really needed in niche cases. 

However, the "refresh_status" service will poll the vehicle directly and then run "poll_api" once the command returns "success" to make sure you have the latest possible data.

**Comment by itchannel** [comment] 2023-11-05 09:27
Fixed in 1.61

**Closed by itchannel** 2023-11-05 09:27 UTC
