### ISSUE TITLE
showing Doors locked even though they are not locked

### ISSUE THREAD

**Issue by doronazl** [itchannel/fordpass-ha#299] opened 2023-09-27 03:07 UTC
every time i park the car it goes to locked status after about 30 min i believe
in reality they are not locked

**Comment by jpettitt** [comment] 2023-09-29 01:42
I'm also seeing lock weirdness - showing locked when it isn't and not being able to lock or unlock from HA (I can lock/unlock from the Fordpass app).  I tried deleting and re-adding the truck (2022 F150) and it didn't change anything.

**Comment by doronazl** [comment] 2023-09-29 10:26
> I'm also seeing lock weirdness - showing locked when it isn't and not being able to lock or unlock from HA (I can lock/unlock from the Fordpass app). I tried deleting and re-adding the truck (2022 F150) and it didn't change anything.

so i made individual buttons for locking and unlocking, this way its not depended on the flase status its showing, you probably know when your car is locked or unlock, just click what you need to, until they fix this, hopefully

**Comment by doronazl** [comment] 2023-10-11 15:57
So got the beta 6.
Not seeing the unlocking/locking states anymore, and like you said, it wont update until next refresh.
So im forced to call service in order to lock or unlock rather than the regular state based lock sensor.
Which is ok i guess as long as its working.

But the door status is quite important when locking the car when its out of sight, better to know the command went through and the doors actually got locked.

@itchannel you think the status will be added back in the future versions?

**Comment by itchannel** [comment] 2023-10-12 08:44
Status will be added in an upcoming release. Now I've pushed 1.53 to live I can start work on ironing out any user interface related bugs.

**Comment by itchannel** [comment] 2023-10-13 20:34
This should be resolved in the latest version 1.57 let me know if it isn't. 

I'll close this issue later if I don't hear anything back.

**Comment by itchannel** [comment] 2023-10-14 09:43
Closing old issue for housekeeping

Please reopen if the issue is still present :)

**Closed by itchannel** 2023-10-14 09:43 UTC

**Comment by fcaronte** [comment] 2023-11-14 14:33
Hi, on my focus mk4 seem the open\close door status is showing opposite, or not update at all, for example in this graph today 14.11.23 at around 7.00 to 7.30 o clock door was opened and then stay closed because I'm at work, here are showing always as open. On ford pass pro app is showing correctly
![Screenshot_20231114-153102.png](https://github.com/itchannel/fordpass-ha/assets/26366403/64764a82-3850-46ed-865a-8a41abd8d489)
