### ISSUE TITLE
Two Accounts

### ISSUE THREAD

**Issue by balronu** [itchannel/fordpass-ha#164] opened 2022-02-15 14:03 UTC
I have two Accounts for two Cars (My Wife and my daughter). But I can use only one Account. See the picture
![704425E1-4232-4341-A48A-355CF6F6B583](https://user-images.githubusercontent.com/81955469/154077526-add384f7-b2cd-44d9-b782-5d8eed66f24d.jpeg)

**Comment by simonsi86** [comment] 2022-02-15 21:02
Same issue as well.

**Comment by itchannel** [comment] 2022-02-15 21:52
Can you please provide a copy of the log so I can see the error. I have two accounts added fine on my instance so will need more information from both of you to troubleshoot

**Comment by simonsi86** [comment] 2022-02-16 18:28
HI
logs below

Simon


This error originated from a custom integration.

Logger: custom_components.fordpass
Source: helpers/update_coordinator.py:219
Integration: FordPass (documentation, issues)
First occurred: 08:01:07 (470 occurrences)
Last logged: 18:26:24

Error fetching fordpass data: Error communicating with FordPass for
WF0NX###########
Error fetching fordpass data: Error communicating with FordPass for
WF02X############

**Comment by simonsi86** [comment] 2022-02-16 18:32
![image](https://user-images.githubusercontent.com/83037829/154332239-ba359df0-3cfe-4cd9-ac5b-c9d41dc0dab6.png)

![image](https://user-images.githubusercontent.com/83037829/154332324-ab1258b0-1f89-4e8c-9b2c-da107caba4b6.png)

**Comment by caleb9707** [comment] 2022-02-18 01:54
Having the same issue here. If I clear the tokens and/or refresh the integration, I can get one or the other to work, but not both at the same time. Here is the log, same as the others

Logger: custom_components.fordpass
Source: helpers/update_coordinator.py:219
Integration: FordPass ([documentation], [issues])
First occurred: 7:48:06 PM (4 occurrences)
Last logged: 7:48:55 PM
Error fetching fordpass data: Error communicating with FordPass for 1F***************

**Comment by itchannel** [comment] 2022-02-21 21:46
Thanks. I know what the issue is and will hopefully bring out a new version this week when I have time to test.

**Comment by simonsi86** [comment] 2022-02-21 21:57
I don't mind testing it as well before you release it

**Comment by darkneo29** [comment] 2022-03-17 10:11
Hello. Any update on this?

**Comment by balronu** [comment] 2022-04-03 07:39
@itchannel are you OK?

**Comment by itchannel** [comment] 2022-04-03 09:45
@balronu Sorry had prior commitments. Please try this version when you have 5 [1.31](https://github.com/itchannel/fordpass-ha/tree/1.31)

**Comment by balronu** [comment] 2022-04-03 10:02
@itchannel It's all OK. Just wanted to make sure nothing happened to you. I downloaded the new version manually and it works. Thanks so much.

**Comment by itchannel** [comment] 2022-04-03 10:04
Great. Once I've fully tested It I'll release to HACS

**Comment by caleb9707** [comment] 2022-04-03 19:17
@itchannel I also installed the new version manually and it works great! Really appreciate your efforts on this. Hope all is well!

**Comment by itchannel** [comment] 2022-06-02 09:11
Closing as this was resolved in the latest version.

**Closed by itchannel** 2022-06-02 09:11 UTC
