### ISSUE TITLE
Step 1 has reached error limit

### ISSUE THREAD

**Issue by kevindery** [itchannel/fordpass-ha#426] opened 2023-11-02 16:12 UTC
Hi i can't remote start or lock the door like i use to i get "Step 1 has reached error limit" error but the fuel level is still accurate.
There is something to do to fix it?

`[140213703355200] Step 1 has reached error limit
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/commands.py", line 230, in handle_call_service
    await hass.services.async_call(
  File "/usr/src/homeassistant/homeassistant/core.py", line 2035, in async_call
    response_data = await coro
                    ^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/core.py", line 2072, in _execute_service
    return await target(service_call)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/entity_component.py", line 235, in handle_service
    return await service.entity_service_call(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 876, in entity_service_call
    response_data = await _handle_entity_call(
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 948, in _handle_entity_call
    result = await task
             ^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/lock/__init__.py", line 99, in _async_lock
    await entity.async_lock(**remove_entity_service_fields(service_call))
  File "/config/custom_components/fordpass/lock.py", line 41, in async_lock
    status = await self.coordinator.hass.async_add_executor_job(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/fordpass/fordpass_new.py", line 636, in lock
    return self.__request_and_poll_command("lock")
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/fordpass/fordpass_new.py", line 694, in __request_and_poll_command
    self.__acquire_token()
  File "/config/custom_components/fordpass/fordpass_new.py", line 383, in __acquire_token
    self.auth()
  File "/config/custom_components/fordpass/fordpass_new.py", line 281, in auth
    raise Exception("Step 1 has reached error limit")
Exception: Step 1 has reached error limit`

**Comment by tcc0** [comment] 2023-11-02 19:09
Same problem for me as well

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/commands.py", line 230, in handle_call_service
    await hass.services.async_call(
  File "/usr/src/homeassistant/homeassistant/core.py", line 2035, in async_call
    response_data = await coro
                    ^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/core.py", line 2072, in _execute_service
    return await target(service_call)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/entity_component.py", line 235, in handle_service
    return await service.entity_service_call(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 876, in entity_service_call
    response_data = await _handle_entity_call(
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 948, in _handle_entity_call
    result = await task
             ^^^^^^^^^^
  File "/config/custom_components/fordpass/switch.py", line 46, in async_turn_on
    await self.coordinator.hass.async_add_executor_job(
  File "/usr/local/lib/python3.11/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/fordpass/fordpass_new.py", line 624, in start
    return self.__request_and_poll_command("remoteStart")
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/fordpass/fordpass_new.py", line 694, in __request_and_poll_command
    self.__acquire_token()
  File "/config/custom_components/fordpass/fordpass_new.py", line 383, in __acquire_token
    self.auth()
  File "/config/custom_components/fordpass/fordpass_new.py", line 281, in auth
    raise Exception("Step 1 has reached error limit")
Exception: Step 1 has reached error limit

**Comment by tcc0** [comment] 2023-11-03 11:37
Yes remote start and locks indeed, the other data is still updating!

And yes, other errors (replaced client_id with blablabla):

Deze fout is ontstaan door een aangepaste integratie.

Logger: urllib3.connectionpool
Source: custom_components/fordpass/fordpass_new.py:97
Integration: FordPass (documentation, issues)
First occurred: 05:31:33 (21 occurrences)
Last logged: 12:32:49

Retrying (Retry(total=9, connect=3, read=None, redirect=None, status=None)) after connection broken by 'ProtocolError('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))': /v1.0/endpoint/default/authorize?redirect_uri=fordapp://userauthorized&response_type=code&scope=openid&max_age=3600&client_id=blablabla&code_challenge=lzxitCHq1_KfFJO8OwnXRnnBcj195_f1rm92OUJNcRA&code_challenge_method=S256
Retrying (Retry(total=9, connect=3, read=None, redirect=None, status=None)) after connection broken by 'ProtocolError('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))': /v1.0/endpoint/default/authorize?redirect_uri=fordapp://userauthorized&response_type=code&scope=openid&max_age=3600&client_id=blablabla&code_challenge=ea8L2Nbv5Nb6PxzOomka1uyzSmJPUfWtY3AneqnCX_M&code_challenge_method=S256
Retrying (Retry(total=9, connect=3, read=None, redirect=None, status=None)) after connection broken by 'ProtocolError('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))': /v1.0/endpoint/default/authorize?redirect_uri=fordapp://userauthorized&response_type=code&scope=openid&max_age=3600&client_id=blablabla&code_challenge=BFU3rtmURYKIXu1S4nVWEDszXHtH_GqHNK4eBol3X1E&code_challenge_method=S256
Retrying (Retry(total=9, connect=3, read=None, redirect=None, status=None)) after connection broken by 'ProtocolError('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))': /v1.0/endpoint/default/authorize?redirect_uri=fordapp://userauthorized&response_type=code&scope=openid&max_age=3600&client_id=blablabla&code_challenge=xm9mpuW8N1f0B2_X4DD_wkJLKe9Ex7KYLg1xVBPgn7o&code_challenge_method=S256
Retrying (Retry(total=9, connect=3, read=None, redirect=None, status=None)) after connection broken by 'ProtocolError('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))': /v1.0/endpoint/default/authorize?redirect_uri=fordapp://userauthorized&response_type=code&scope=openid&max_age=3600&client_id=blablabla&code_challenge=3l_O0FR6ThbXOhqS1z_UUGyP5gh6sfCCvTwM4iToitA&code_challenge_method=S256

**Comment by kevindery** [comment] 2023-11-03 18:06
There's the full logs, i'm still new to HA 😅
`2023-11-03 13:10:14.873 WARNING (SyncWorker_3) [homeassistant.loader] We found a custom integration ui_lovelace_minimalist which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2023-11-03 13:10:14.875 WARNING (SyncWorker_3) [homeassistant.loader] We found a custom integration fordpass which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2023-11-03 13:10:14.878 WARNING (SyncWorker_3) [homeassistant.loader] We found a custom integration ember_mug which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2023-11-03 13:10:14.880 WARNING (SyncWorker_3) [homeassistant.loader] We found a custom integration localtuya which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2023-11-03 13:10:14.881 WARNING (SyncWorker_3) [homeassistant.loader] We found a custom integration hacs which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2023-11-03 13:10:14.882 WARNING (SyncWorker_3) [homeassistant.loader] We found a custom integration webrtc which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2023-11-03 13:10:16.116 WARNING (Recorder) [homeassistant.components.recorder.util] The system could not validate that the sqlite3 database at //config/home-assistant_v2.db was shutdown cleanly
2023-11-03 13:10:16.142 WARNING (Recorder) [homeassistant.components.recorder.util] Ended unfinished session (id=19 from 2023-11-01 21:16:57.219787)
2023-11-03 13:10:21.199 WARNING (MainThread) [hass_nabucasa.cloud_api] Fetched https://alexa-api.nabucasa.com/access_token (400)
2023-11-03 13:14:13.467 ERROR (stream_worker) [homeassistant.components.stream.stream.camera.kitchen] Error from stream worker: Error opening stream (HTTP_NOT_FOUND, Server returned 404 Not Found) rtsps://stream-ue1-bravo.dropcam.com:443/sdm_live_stream/CiUA2vuxr8TL3pmIE3RmV_rFHIaqeEkhnyk3qxOlbZQBhLRuxtXiEnEAJV7BO4AXVQM283pgb3mffTSxgeghj_ew3oL3QKe3YBYDyN1iK23MT0bwO1q5f4H0u-MIJJ72u7MHrH2jZDEPVFKuMrMf7W0csUwKmpLU_qS6aHu8sW3hZCSDZFhEJSLSI0-BGkzLMlkZ4oi5d5-Qsw?auth=****
2023-11-03 13:14:32.631 ERROR (MainThread) [frontend.js.latest.202310301] Uncaught error from Chrome 118.0.0.0 on Windows 10
TypeError: Cannot read properties of undefined (reading 'domain')
_keyFunction (src/panels/config/integrations/dialog-add-integration.ts:455:16)
keyFunction (src/virtualize.ts:116:41)
r (src/directives/repeat.ts:56:28)
ct (src/directives/repeat.ts:93:52)
update (src/directive.ts:134:16)
_$AS (src/lit-html.ts:1085:23)
S (src/lit-html.ts:1362:12)
_$AI (src/async-directive.ts:366:18)
setValue (src/virtualize.ts:139:13)
dispatchEvent (src/Virtualizer.ts:802:23)
2023-11-03 13:14:33.817 ERROR (MainThread) [frontend.js.latest.202310301] Uncaught error from Chrome 118.0.0.0 on Windows 10
TypeError: Cannot read properties of undefined (reading 'domain')
_keyFunction (src/panels/config/integrations/dialog-add-integration.ts:455:16)
keyFunction (src/virtualize.ts:116:41)
r (src/directives/repeat.ts:56:28)
ct (src/directives/repeat.ts:93:52)
update (src/directive.ts:134:16)
_$AS (src/lit-html.ts:1085:23)
S (src/lit-html.ts:1362:12)
_$AI (src/async-directive.ts:366:18)
setValue (src/virtualize.ts:139:13)
dispatchEvent (src/Virtualizer.ts:802:23)
2023-11-03 13:25:27.516 WARNING (MainThread) [custom_components.fordpass] cannot access local variable 'response' where it is not associated with a value
2023-11-03 13:25:27.516 WARNING (MainThread) [custom_components.fordpass] Error communicating with FordPass for 1FTFW1E52MKE01417
2023-11-03 13:25:27.516 WARNING (MainThread) [custom_components.fordpass] Returning Stale data to prevent unavaliable status
2023-11-03 13:40:27.891 WARNING (SyncWorker_1) [urllib3.connectionpool] Retrying (Retry(total=9, connect=3, read=None, redirect=None, status=None)) after connection broken by 'ProtocolError('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))': /v1.0/endpoint/default/authorize?redirect_uri=fordapp://userauthorized&response_type=code&scope=openid&max_age=3600&client_id=9fb503e0-715b-47e8-adfd-ad4b7770f73b&code_challenge=OJ1evBQPdRGgkelUUakag71Af-P6sWjMzb92ZL3LS1w&code_challenge_method=S256
2023-11-03 13:40:33.667 WARNING (MainThread) [custom_components.fordpass] Step 1 has reached error limit
2023-11-03 13:40:33.667 WARNING (MainThread) [custom_components.fordpass] Error communicating with FordPass for 1FTFW1E52MKE01417
2023-11-03 13:40:33.667 WARNING (MainThread) [custom_components.fordpass] Returning Stale data to prevent unavaliable status
2023-11-03 13:40:53.559 WARNING (MainThread) [google_nest_sdm.event_media] Failure when pre-fetching event 'AVPHwEsE4GHiAoVK2jKNy_SnVbWJJfcTemx3ZD9tTnFJSOLJMwu6D6DExJ5nTCZb7Kw8pzzQ_XGjogLy8i4TTnHpUWpN': Internal Server Error
2023-11-03 13:55:33.587 WARNING (SyncWorker_2) [urllib3.connectionpool] Retrying (Retry(total=9, connect=3, read=None, redirect=None, status=None)) after connection broken by 'ProtocolError('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))': /v1.0/endpoint/default/authorize?redirect_uri=fordapp://userauthorized&response_type=code&scope=openid&max_age=3600&client_id=9fb503e0-715b-47e8-adfd-ad4b7770f73b&code_challenge=00DAbn7zf95ll-kn87Lcdmi4LdsgYsbxDqqIcou5D-4&code_challenge_method=S256
2023-11-03 13:55:34.229 WARNING (MainThread) [custom_components.fordpass] Step 1 has reached error limit
2023-11-03 13:55:34.230 WARNING (MainThread) [custom_components.fordpass] Error communicating with FordPass for 1FTFW1E52MKE01417
2023-11-03 13:55:34.230 WARNING (MainThread) [custom_components.fordpass] Returning Stale data to prevent unavaliable status
2023-11-03 14:00:15.184 ERROR (MainThread) [homeassistant.components.websocket_api.http.connection] [140576621448896] Step 1 has reached error limit
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/commands.py", line 230, in handle_call_service
    await hass.services.async_call(
  File "/usr/src/homeassistant/homeassistant/core.py", line 2035, in async_call
    response_data = await coro
                    ^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/core.py", line 2072, in _execute_service
    return await target(service_call)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/entity_component.py", line 235, in handle_service
    return await service.entity_service_call(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 876, in entity_service_call
    response_data = await _handle_entity_call(
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 948, in _handle_entity_call
    result = await task
             ^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/lock/__init__.py", line 99, in _async_lock
    await entity.async_lock(**remove_entity_service_fields(service_call))
  File "/config/custom_components/fordpass/lock.py", line 41, in async_lock
    status = await self.coordinator.hass.async_add_executor_job(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/fordpass/fordpass_new.py", line 636, in lock
    return self.__request_and_poll_command("lock")
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/fordpass/fordpass_new.py", line 694, in __request_and_poll_command
    self.__acquire_token()
  File "/config/custom_components/fordpass/fordpass_new.py", line 383, in __acquire_token
    self.auth()
  File "/config/custom_components/fordpass/fordpass_new.py", line 281, in auth
    raise Exception("Step 1 has reached error limit")
Exception: Step 1 has reached error limit
`

**Comment by itchannel** [comment] 2023-11-05 00:50
Does this happen every time you try locking/unlocking or only every so often?

The error indicates that it is having problems connecting to the Fordpass authentication endpoint so is timing out. 

Can anyone experiencing the issue please provide me with the current information so I can try and narrow down the cause. 

 - Model and Year of vehicle
 - Version of Home Assistant (Including is it HAOS, Docker etc)
 - Version of fordpass integration (Latest 1.61)
 - Region/Country you are from and the region you choose when setting it up. 
 - Is it only locking/unlocking and remote start that is affected
 - Output from enabling debugging and trying to lock/unlock (https://github.com/itchannel/fordpass-ha/wiki/Obtaining-Integration-Logs)

Hopefully with this information I will be able to narrow down the issue as it seems to only be affecting a small number and I've been unable to replicate it on my end.

**Comment by tcc0** [comment] 2023-11-05 09:20
I have this problem everytime I want to control something (doors, lock, update status) and since the last couple of versions.

Kinda weird, looks like read-only is always working (getting data from the cloud) but writing/controlling something doesn't work (opening, locking, refreshing)

The info is always(!) automatically updating when I drove the car, but when I manually press the refresh car button for instance I get the 3 log entries as well:

Error doing job: Task exception was never retrieved
08:45:15 – (FOUT) FordPass (aangepaste integratie)

FordPass Refresh Status: Error executing script. Unexpected error for call_service at pos 1: Step 1 has reached error limit
08:45:15 – (FOUT) Script

Retrying (Retry(total=9, connect=3, read=None, redirect=None, status=None)) after connection broken by 'ProtocolError('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))': /v1.0/endpoint/default/authorize?redirect_uri=fordapp://userauthorized&response_type=code&scope=openid&max_age=3600&client_id=blablabla&code_challenge=y5SHDToMK6kvnS3O129NM2OZWrLy-OgRhgIfEx4swOo&code_challenge_method=S256
08:45:14 – (WAARSCHUWING) FordPass (aangepaste integratie)

Removed the config, removed the fordpass addon and tried again using

Nov 2018 Ford Focus MK4 (2019 model)
HA Core 2023.11.0
FordPass  1.61
Europe/The Netherlands, configured region UK&Europe

Now after importing the VIN (Kun kjøretøy som ikke er lagt til for øyeblikket, vises???) I get some errors about not generating unique ID's (replaced my VIN with blablabla):

Logger: homeassistant.components.lock
Source: helpers/entity_platform.py:610
Integration: Slot (documentation, issues)
First occurred: 09:11:20 (1 occurrences)
Last logged: 09:11:20
Platform fordpass does not generate unique IDs. ID blablabla-fordpass_doorlock already exists - ignoring lock.fordpass_doorlock

Logger: homeassistant.components.switch
Source: helpers/entity_platform.py:610
Integration: Schakelaar (documentation, issues)
First occurred: 09:11:20 (1 occurrences)
Last logged: 09:11:20
Platform fordpass does not generate unique IDs. ID blablabla-fordpass_ignition already exists - ignoring switch.fordpass_ignition_switch

Logger: homeassistant.components.device_tracker
Source: helpers/entity_platform.py:610
Integration: Apparaattracker (documentation, issues)
First occurred: 09:11:20 (1 occurrences)
Last logged: 09:11:20
Platform fordpass does not generate unique IDs. ID blablabla-fordpass_tracker already exists - ignoring device_tracker.fordpass_tracker

Logger: homeassistant.components.sensor
Source: helpers/entity_platform.py:610
Integration: Sensor (documentation, issues)
First occurred: 09:11:20 (15 occurrences)
Last logged: 09:11:22
Platform fordpass does not generate unique IDs. ID blablabla-fordpass_indicators already exists - ignoring sensor.fordpass_indicators
Platform fordpass does not generate unique IDs. ID blablabla-fordpass_coolantTemp already exists - ignoring sensor.fordpass_coolanttemp
Platform fordpass does not generate unique IDs. ID blablabla-fordpass_remoteStartStatus already exists - ignoring sensor.fordpass_remotestartstatus
Platform fordpass does not generate unique IDs. ID blablabla-fordpass_messages already exists - ignoring sensor.fordpass_messages
Platform fordpass does not generate unique IDs. ID blablabla-fordpass_odometer already exists - ignoring sensor.fordpass_odometer

**Comment by itchannel** [comment] 2023-11-05 09:26
@tcc0 The already exists errors will fix themselves after a restart it's because on removal HA isn't releasing them correctly. It's on my list to look into at some point. 

The timeout issue seems to be that the API stops responding "'ProtocolError('Connection aborted.',". I've added a timeout of 10 seconds in the loop just to see if that helps as well as logging the step1 URL. If you have five can you replace your fordpass_new.py with the one linked https://github.com/itchannel/fordpass-ha/blob/1.62/custom_components/fordpass/fordpass_new.py

Otherwise I'm happy to screenshare or walkthrough with someone to do some debug testing as I can't replicate on my end.

**Comment by tcc0** [comment] 2023-11-05 09:44
Upgraded to Home Assistant 2023.11.1 meanwhile and after that restarted I was able to lock and unlock the doors and refresh the info without the errors in the log.

Anyway, replaced fordpass_new.py with the new version and restarted Home Assitant.

Will keep you posted, thanks for your great support already!

**Comment by tcc0** [comment] 2023-11-05 11:04
Got the error again while just running HA:

Logboek Details (WAARSCHUWING)
Deze fout is ontstaan door een aangepaste integratie.

Logger: urllib3.connectionpool
Source: custom_components/fordpass/fordpass_new.py:98
Integration: FordPass ([documentation](https://github.com/itchannel/fordpass-ha), [issues](https://github.com/itchannel/fordpass-ha/issues))
First occurred: 11:12:35 (2 occurrences)
Last logged: 11:58:06

Retrying (Retry(total=9, connect=3, read=None, redirect=None, status=None)) after connection broken by 'ProtocolError('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))': /v1.0/endpoint/default/authorize?redirect_uri=fordapp://userauthorized&response_type=code&scope=openid&max_age=3600&client_id=9fb503e0-715b-47e8-adfd-ad4b7770f73b&code_challenge=qCaji6Ls2rrmOl9PDYE_xVps4XMlgJDBhSndpFA97XM&code_challenge_method=S256
Retrying (Retry(total=9, connect=3, read=None, redirect=None, status=None)) after connection broken by 'ProtocolError('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))': /v1.0/endpoint/default/authorize?redirect_uri=fordapp://userauthorized&response_type=code&scope=openid&max_age=3600&client_id=9fb503e0-715b-47e8-adfd-ad4b7770f73b&code_challenge=XazwsahSohJzX-C4RtjQDB5f-s5G9dhQB5X6_ikDres&code_challenge_method=S256

**Comment by MartyTremblay** [comment] 2023-11-05 12:45
Same issue here for a 2018 Ford Expedition. Error logs look almost identical.

**Comment by itchannel** [comment] 2023-11-05 21:20
Can someone please enabled debug logging (https://github.com/itchannel/fordpass-ha/wiki/Obtaining-Integration-Logs) and provide me with a full copy of the log. There should be debug code in it so we can see more than just the exception that is raised. You can email me at github@itchannel.me if it contains any sensitive info. 

The issue appears to be potential rate limiting on the API or some instability as the error indicates the connection was closed with the initial endpoint as part of the authentication check. 

Can anyone else please provide what region they are from so far I have one user with "UK&Europe" having the issue.

**Comment by kevindery** [comment] 2023-11-05 21:31
For me it look like i can't send data(remote start, locking door) but can can read(odometer, fuel)
Ford F150 2021 lariat, Canada
here's the debug log for trying to lock the door and after remote start
[home-assistant_fordpass_2023-11-05T21-23-16.808Z.log](https://github.com/itchannel/fordpass-ha/files/13260849/home-assistant_fordpass_2023-11-05T21-23-16.808Z.log)

Thank you for your awesome support :D

**Comment by tcc0** [comment] 2023-11-06 07:38
Missed the debug past, my bad, just emailed you the debug log!

**Comment by bradleyd444** [comment] 2023-11-06 13:07
I am sending my debug log with the error on both vehicle start and door Lock.

**Comment by tcc0** [comment] 2023-11-07 08:07
Emailed you another debug log, this time one including everything, thanks again!

**Comment by ziptbm** [comment] 2023-11-14 13:18
@itchannel depending on time, I’d be willing to screen share as I’m seeing this as well.   Started for me today. I can grab logs when I’m not on mobile helpful.  They look just like the ones above for both of my vehicles.

**Comment by tcc0** [comment] 2023-11-14 15:42
For what it's worth;

Running 1.63 Beta 1 since 14:03 and still able to lock, update, etc without errors, it's 16:41 now.
Will keep you posted if it fails or continue to work.

Thanks for your time

**Comment by tcc0** [comment] 2023-11-14 20:00
Still work ing without a single hickup, very stable for me 👌🏼

**Comment by MartyTremblay** [comment] 2023-11-16 11:28
Same here. Solid as a rock for the past 2 days!

**Comment by SquidBytes** [comment] 2024-05-09 19:38
Looks like this was resolved at the time. 
Thins may have changed due to recent issues - but for now I'm going to close this specific issue

**Closed by SquidBytes** 2024-05-09 19:38 UTC
