### ISSUE TITLE
sensor reading are not continuous anymore but interrupted by "unavailable" on a 20 min frequency.

### ISSUE THREAD

**Issue by xaviersand** [itchannel/fordpass-ha#269] opened 2023-07-11 17:04 UTC
i'm not sure if there is a bug or if i made a mistake.
Some day, the fordpass stopped working, there was an update for the fordpass so i updated; i started working again --> happy.
Downside is, the values used to be continuous, when now they are cut with "unavailable" statuses (which is kind of annoying)
![image](https://github.com/itchannel/fordpass-ha/assets/8404389/44a661c2-dc21-4dd0-a4cf-c6f96e886a42)

the interval are very constants, the colored value (open / closed in the example here), each bar are a duration between 20'20"and 20'40" seconds) (open/closed/unavailable) , so, let's say: 20 minutes;   (my interval poll is 600s --> 10 min) --> it's kind of weird; or it means "2 calls are working, then 2 call are failing, and so on"
![image](https://github.com/itchannel/fordpass-ha/assets/8404389/dd0a1a23-813d-4a93-bdb9-4aa0a6955f29)

do you know if i may have mistakenly changed something or did someone else had something similar ?
I also updated the ha.core, but i think it was "after the bug already appeared", i was like "lets try this too.
Also, this is only with the ford_pass integration, other sensors don't suffer this behaviour..

**Comment by coltography** [comment] 2023-07-14 20:36
I have this same issue and it's driving me nuts. It also affects doors unlocking etc, if I don't catch it in that ~20min window I cant lock my vehicle.

**Comment by itchannel** [comment] 2023-07-18 01:33
It's because the Fordpass API has failed to respond so the integration sets the sensor to "Unavailable". You could try editing line 234 in sensor.py and changing the value from 
``` 
self._available = False  # Mark as unavailable
```

to 
```
self._available = True
```

Which should not mark the entity as unavailable when the update fails. However I would have to further test this my end as I used to get the same issues as you but I haven't had API issues in a long time.

**Comment by notlistening** [comment] 2023-08-02 21:30
Also seeing this issue. The integration should implement exponential back off when fetching the data until it succeeds.

**Comment by notlistening** [comment] 2023-08-03 16:39
Right looking at how the requests are failing on my system (Europe Region) I can see I get 30:01 mins of good connectivity and then 15:01 mins of unavailable state. 

Reading the source  I can see that the auth token is refreshed when Ford says it 'should' expire, the integration authors has diligently implemented Fords intention and set his token expiry to the time they say it will expired. 

However from the very clear pattern I see in HA I think Ford in Europe at least are expiring their access token after 30 mins not the advertised 45 mins.

I have hard coded my token refresh time to 30 minutes and I await to see if I get the unavailable state returning, testing is in progress. 24 hrs later I have had 100% data consistency and have not seen the data return to unavailable. 

This is a bug in Fords API data and the advertised access tokens expiry time does not match the actual tokens expiry time and should be reported directly to Ford, good luck with that. 

However this is NOT a bug with this integration, it might be possible to set a customer expiry time inside the integration config until Ford pull their finger out.

**Comment by Rodelkoenig** [comment] 2023-08-14 23:44
> Right looking at how the requests are failing on my system (Europe Region) I can see I get 30:01 mins of good connectivity and then 15:01 mins of unavailable state.
> 
> Reading the source I can see that the auth token is refreshed when Ford says it 'should' expire, the integration authors has diligently implemented Fords intention and set his token expiry to the time they say it will expired.
> 
> However from the very clear pattern I see in HA I think Ford in Europe at least are expiring their access token after 30 mins not the advertised 45 mins.
> 
> I have hard coded my token refresh time to 30 minutes and I await to see if I get the unavailable state returning, testing is in progress. 24 hrs later I have had 100% data consistency and have not seen the data return to unavailable.

Got exactly the same issue with identical Intervalls (30:01 and 15:01), Europe / Germany.

Could you please share a snippet where and how you modified the Code as a workaround?

Is it enough to Change the py files in HA File Editor and restart HA Afterwards?

**Comment by itchannel** [comment] 2023-08-24 08:48
@notlistening interesting to see how you got on with this. I wonder if it depends on peoples HA time if it's not in sync then it could cause the token issue you mentioned as I'm comparing the HA time to the fordpass token expiry.

**Comment by notlistening** [comment] 2023-08-24 11:23
So I am not longer getting the unavailable data blocks. However the data does seem to be out of sync with the state of the car. For example the doors are locked and alarm set but the data in HA indicates they are unlocked, the alarm is NOT SET etc. It seems like if HA is restarted then the data is not reapplied (maybe), it's possible my changes also stopped it from working correctly :) more than likely.

**Comment by notlistening** [comment] 2023-08-24 12:00
@itchannel assuming the Ford servers are sync'd and the HA server is also in sync with network time then this should be okay. I know the OS i run on uses NTP. There shouldn't be any problem, but 15 minutes isn't a time sync issue it's too long. Almost like someone adjusted the token server to 30 mins and forgot to change the ford pass API code @Ford.

**Comment by Rodelkoenig** [comment] 2023-08-24 20:21
@itchannel  here is my DEBUG log for the failing refresh. I am not sure if this is really tied to some wrong token expiry, because it WANTS to refresh but somehow fails:

`2023-08-24 21:46:52.237 DEBUG (SyncWorker_3) [custom_components.fordpass.fordpass_new] No token, or has expired, requesting new token
2023-08-24 21:46:52.246 WARNING (MainThread) [custom_components.fordpass] ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))
2023-08-24 21:46:52.248 WARNING (MainThread) [custom_components.fordpass] Error communicating with FordPass for XXX
2023-08-24 21:46:52.249 ERROR (MainThread) [custom_components.fordpass] Error fetching fordpass data: Error communicating with FordPass for XXX
2023-08-24 21:46:52.251 DEBUG (MainThread) [custom_components.fordpass] Finished fetching fordpass data in 0.016 seconds (success: False)`

So my "cycle" is as follows:
1st refresh: "no token or expired", sucessfully fetching token, getting data
2nd refresh after 900s: "token valid", getting data
3rd refresh after 900s: "no token or expired", connection aborted

**Comment by notlistening** [comment] 2023-08-24 20:58
@Rodelkoenig there are two cycles going on in the code:
1. One loop refreshing the data every 15 mins
2. Another loop refreshing the token every 45 minutes (by default)

If you were to apply my patch directly into the python and restart HA I would hope those errors would disappear for you. 

Can you report back if it helps to fix your problem too?

**Comment by Rodelkoenig** [comment] 2023-08-25 07:46
@notlistening 

Unfortunately it didnt Change anything for me :/ modified the Code with HA File Editor and restarted HA but still Same 30min-15min cycle.

Did you get the same Error as me before?

**Comment by xaviersand** [comment] 2023-08-25 08:41
Fyi, same for me, I actually tested that 2 weeks already without success. I was wondering if the files I found were the one used by home assistant or not. I updated the following file: `/config/custom_components/fordpass/fordpass_new.py` using the file editor ui.
![image](https://github.com/itchannel/fordpass-ha/assets/8404389/84a3c951-bd70-435b-a799-177d290b235f)

**Comment by Rodelkoenig** [comment] 2023-08-29 20:56
FYI i have a workaround for me now.

Wrapped the refreshToken-method in a for-loop with 3 attempts (and a fallback-call to auth()-Method after those).
In the last 24h it ALWAYS failed EXACTLY one time and suceeded in the first retry ... no idea why this is happening.

**Comment by SquidBytes** [comment] 2023-10-30 19:05
I'm going to close this because there have been large changes since August, when the last comment was.
Please open a new issue for any new issues :)

**Closed by SquidBytes** 2023-10-30 19:05 UTC
